
/*
Simplified installation of mayaHooks, just drag this into maya to start the installation.


All the code for the mayaHooks python module is compressed here with zlib
and base64.  I tried to have it all as plain text but escaping multiline code
within multiline code that contained multiline code got too complicated.
*/
python("\n\
import json\n\
import base64\n\
import datetime\n\
import os\n\
import zlib\n\
\n\
from maya import cmds\n\
\n\
try:\n\
    import mayaHooks\n\
    exists = True\n\
except:\n\
    exists = False\n\
buildTime = '2019-11-21 02:26:13.001010'\n\
if exists:\n\
    existinInfo = os.path.join(os.path.dirname( mayaHooks.__file__ ) + '-info', 'info.json')\n\
    existingBuildTime = None\n\
    if os.path.exists(existinInfo):\n\
        try:\n\
            with open(existinInfo, 'r') as fid:\n\
                data = json.load(fid)\n\
\n\
            existingBuildTime = data.get('utc_build_time', None)\n\
        except Exception:\n\
            pass\n\
\n\
    if existingBuildTime:\n\
\n\
        if buildTime > existingBuildTime:\n\
            res = cmds.confirmDialog(m='Update with this newer version of mayaHooks?\\n\\nExisting build time: {}\\nThis new build time: {}'.format(existingBuildTime, buildTime),\n\
                b=['Upgrade', 'Cancel'])\n\
            if res != 'Upgrade':\n\
                raise Exception('Canceled install')\n\
\n\
        else:\n\
            res = cmds.confirmDialog(m='Downgrade to this older version of mayaHooks?\\n\\nExisting build time: {}\\nThis old build time: {}'.format(existingBuildTime, buildTime),\n\
                b=['Downgrade', 'Cancel'])\n\
            if res != 'Downgrade':\n\
                raise Exception('Canceled install')\n\
\n\
    else:\n\
        res = cmds.confirmDialog(m='An existing mayaHooks was found but the build time could not be determined.\\n\\nUpdate to this version?    {}'.format(buildTime),\n\
            b=['Update', 'Cancel'])\n\
        if res != 'Update':\n\
            raise Exception('Canceled install')\n\
\n\
scriptFolder = os.environ['maya_app_dir'] + '/scripts'\n\
\n\
# write files to scriptFolder + '/mayaHooks'\n\
\n\
allFiles = '''eNrtfX1f20iS8FfpgZ2VnXEEebmZW2aZPQIm8bMEOGwmkwN+jmzLoMG2vJIMYXK5z/7US79KLdsk\n\
2XueP3budgZLrerq7urqqup6+bQxjR6iN2l6m28ls7yIJpPDLJ2eZ5Nw/rCxIzbG8EskqUim8zQr\n\
xKuHIs47J5fZ5Uw+maTX18ns2nqyyCaTZPDcevJHMh8nkxif4P8IJvaroA6no9x5Gao3Eqf9NItr\n\
XyLC/5XMFQBASOwqtMLruDiCP+Os0e/Pomnc7zdlozCHV/FdPGmotgftV+ev6bWAfxS8UTwW2WLW\n\
gGE1d9TLIAjUn73oNs5FJK6T4mYxCIeAITRtiUlyG+v2CqD6+6Yo5vnO1pb5aGseFcM0u09mW+M0\n\
z5OJ6h+bn2TQAUAVRQp/wHQKnM/Qg80oKiIYfhZHI1hEmBbC24a1eQ99qiUJocUh/LchF7aB3zdb\n\
IsiCpohyUcTTuR7EJv4rmY3TFv0bEL6BrqwlCrHbDrzqzLBn/NjpGtf81zjLk3RW+jDKbxvCwUE4\n\
C0E9j8UsLWwgzvRmcbHIZuWP5tHwNrqO/x4/mB4lwYTyJ6IqSuO3MXWGAERTAK3kJfwnaTTqylcN\n\
5wO71WIO4OOGgtGysHO6bNnjytNFNox3kabUYz01uHGAeGbjJJseJBEQcmO6G3S4SwFUNZ/ERfxd\n\
UJlLTdguneyU222K13EhiptYoSpoC+IDaG+tTGAoOYAx41tndXDDjeLB4roRnMXDOLmLR3LHiGg0\n\
yuI8N0haiw1gwng2ypFmG8E0yos4C4F2g6YDHf/B7fHDrgi2omx4A/C3rNblYUF/83SWx7CKkluF\n\
8N90Hs/0dqkgjV/EMKejeEd8+hyE4zSbRkVDgQrxjUW1yVg4r8R3u+L59rZLslECOLQ/DuN5Acve\n\
CGApALYkZZgh+hAeIBHBSol0jDBaIhoA/wMS0lgQx3FRcTe9OExmIxHB/3DJaQFxD4e/50DhyAkE\n\
QBJ3kuTxVYWjSOD4faNZnVFEmRpvtIQ5VZDunyK4Ld0dHiuf9Pcbi2LYHyySyahfJNP4Et5ebjzf\n\
fvaXp8+2nz77UWy/3Hn5bzsv/hL+5ad/297evtzALz87fWzZe4yPLckR6QzSw4SNUsSzIt9RrzQW\n\
W1tA57M4g905YgrPi6yBo4kRqRBwnKX3DZspLcV7+6V49tPO8+2d7e3wxfOfCO+W+RQx78u5Nh9e\n\
bsAydcZiDlMNaLZEOps8CBhXep8rNhIhneApUNxEhVoumhE1JvU/NTuKK9EUVAZ+uQEbdspYfHIO\n\
q435CM6g8mN+xSyJMedzCWhHnUrWSMtf9JE8GObGNB0l4yQe4U+c7DQP8UDBA3uKE9poNsVnmJAT\n\
nIT4Y5IXOe6ppAjwsFXihNsLLomcqMcuigvki9YV//msfny2lpsX15pJvVj6D0mvRHr9/ngBmwlE\n\
FSXoRIM8nSyKuM+/W2KU3CV0UACxJLMCPpgNi8Ssr5Kr0skkphe59VQRQq0Al9qt85tFwcKIfICn\n\
upr+L5XvHPagWsF5FC0mRXeYJfMiPwViACHKOldb4j5Livj/5Dju895+/9V55+igf9A+3Ds/6j1K\n\
/NtcIf8xINO1vbHw2BwDMz3lA1Gf+itP9d1jOEC8IuQZM09kyqNkWCCbt45clF1gf+HXvAPEKI3z\n\
WVDwtghBPKTjA6j+QYsp83iYjB8IjC3LWAdJHtNBCeP2YAT91MlZRfZQOXsl91dTcGF9e3VhhnFl\n\
fxfTsWdOvzqgOO7yaYNnlS0vqalCPqmxCIFYpiCN7ZTkCmtaobX6sq579d43jNLhpzC1KWV4Ew9v\n\
pUAWj14BXyl6yN2+glo6DnWIRB8O8aglUcmZT7qsrCXiCYgbCNe35HOXnmETfRGV+8T2MmhAGbHw\n\
iO/e1XZXQh9osLcbgTvEwMMYmuUlWVsKF0+e3N5H2XXuXQbQF4odMQbtj/gSgJLnUguXZya7gWey\n\
Iw8I9d8oz+OscDdqTvKvbzo0re8aUoc/JPtsOCOwToDwJBvFWTw6AA7TaDZroAJQBd8Gak/Ro2Eq\n\
vUdOZrmV5up6SSpL5uqVcNykg9+bll6qdPAPUp390CLipTUhkRcJCH/hxrlJrm9g7cQEmb8lBWNL\n\
2jak2CbMj6EvvVlGwKhQ47UnQE4Qsu3GBLhx02ZRYzxyEBJjHOJPbFTiSfMoK2i/4fswn08SIOyt\n\
ij5EzS6ePrsCbfMeTrSm2AV1R+MfVDgY4XsB45w16NumuBJhNActZ9Sgvpx5VkgDExkTG4UzOR41\n\
CIhipRVeirDHTfGLeFbln2XlppemQOKzB1vxSBeolbCGmeNkjdMJUBSj3hKLWTQA1QTk3RHosdk0\n\
meGPuVw6SV6Bo+koGwXMJ3ZBmnneUCtAysv4YvvKEuUtFsPGDXxf4UHl0Ryn1jjuo5zHYqM8z9Jh\n\
HI8CLzWfw44HTraY74OuVqFoez3WoyHUl5F6JGlYSvMCesqxpz6qhaAfeXRnOXx7kjR9eDixUa40\n\
T539wRuTxbYR7C84i9K0QDAtkS8GoyTbDQIvJz3Hj3PxQX7+AUZLK06yzWttJKDDHV4BHcSjBHkr\n\
wIR9mGbAlO5vkuGNPnJwDwNPHTGkD9z9ByBpIrRhmuF3itbgHLGO0LA85vbHImPGnqNRbxjPhnGL\n\
1hBHFoH8Ol8UMAEISkK83PgrYv/L1l/VFPzCOvDlRrjkGJD0fMhAdmkGxA8CWAH8W0EydqVxqlu6\n\
X8In1F3gOYqVmsUaVcNAcYmCpf4wmxZZHNutVoN0cFkG1W3os1CVbDBEJ3Nk458+4waDf0vCutz4\n\
9PlyQ1tDSnTIjawdjyrMQYITp5SZcHo7wr+NYcNrJdWAlX10nIycEcJvmAcgmCFSU0N21PSZgWHm\n\
GDFXDIJlBrzUnP6eJjMFRZOCHI/6DKU6Hwz5WXlCRzHaBP9zES/wsL+4Ktu79eGF2w3wQGYD3TUQ\n\
avncouPQwRVbAQctn12qTZIjKPyzyoRm8f0BUnwJIq+hC5FP/T//+c/iIEVFqAA95hb/TbLlDLgu\n\
7P08gZ1aFpV59ObMKeBgLEOu0rRErYozUVN6QEABcTUEWKmQewp8XwD0LMbNrAC3NJCmr721ZOr8\n\
rm2/aYDPiVQV7uWGcjMO0/mD3I51rSsEZhlo1+Qn1sinIKsBEeQ+ruK7KnEnjLF0CMTAQTIRtcCQ\n\
qJVoZ82ogyd1NE3vuKMKUyrrvi5DK+/2pRouGW6Apx3vvTpqi96JOGgftXtt0GB8TAOPM/vMfdV+\n\
3Tnuvzk5+TtQXbAp+Pfbvfd79LBLZNc+PrCa4K9SA+cEVwJJewTi5yQd3ikd4haFfqCLHjA2s6oo\n\
/OlGIe0jKXAMF3mRTndKYkZFgNqnZgiEjJqs7+SL+ZzkTvEQF65gB1KP3SUJv2y8DGq4Ujy7S7J0\n\
dhGQvRU2Th/oLrgiPpqzlWlLDxsFo1qOuh5M5M0Wgiu7qR5xwgG7gwCX9Om7p7D6d9HxNbax0gux\n\
Qx9q8i/dvlUO+zInrwOPNiuCQF+CFgkSFCnNSeFqOnTw0lUM7/Xg3n/UquOW1MdGcHk5c+nlBiS0\n\
OEOihZWz9gssC40QyNrIA9TI+gIaIUD4ryR864neVvKR3WkF+Ro5YQKaDJtYRiRu0+/qrQptK2hm\n\
mwGA+5ee2AwuaRFs5HHxbDGlK40GQXeXaZP5D74BLI+Ojjqd42PkPtylZX4gvRjb2ZvcTEKzJRqV\n\
b5qtZV+UhYNyU7MO1UNEzUjiHlAoTD0W8QpsntkE1vVZ+dUAFunWvVDbkz1iL/hlEV0L0L1iqdSC\n\
rpHF80kkRRDSvWzRz4stwrGeVUnmgr7bgXZXJOF9LNhewPTTyxZVnW0TQIkB7O7bvIQfixIaPb5W\n\
igkJaYF2vAzcWS7j7McXb2TXxFLNp9alxQD0qllKHQC2I5L0RoD27AHlvWvWseO7eAaLMBwmI/gj\n\
mvBQ6HzHg6leSC6fRyhNnrX3jkSv/VvPZUn+a/ZzremjrYnmK0uubwohVx0wh6NU2FwQ2AX8//t0\n\
AYxiMiFBFdtNo9kCrff8QYIqS8xkw+cHPU8zFynewCJ4ixbIfJHxBx+qskAYhh9opT6UhYAPii5A\n\
aRregLJ9ilfmyvQFyuwkvceJpkvvQPi6J9bZXO2HsS5XNxwdNGSW75h7iYoSpSQXKd138rP4OsEr\n\
/3hk2SurRhUWGk75SK9eOjWUVNHUh7qB5sKwVBV5HtrANcLyBI5H9X3SFSiRWTRIF0Xjbpd2CYx6\n\
CRIargcPt8/mEq16n4fCH6JrA1Ao/cuAL73TerYZbEsOvOV2bP20FlBakeTnwvgdQKvyNTYusFSo\n\
QQl/FeXJEA3BqImTq87OUn1dyGY1Dk1ef6YVPkyWoWY/BYYDxJlpO4xaBZDPSFtRYJt+CYmttzhR\n\
O58+14HdsSZcwWvVtC3tEimz1cCtaI5SJQGWOx/eBhU9SoIBuQkll4uSsfpi+8oxV+LEWcZKbaA0\n\
hsmtfj+ZJUW/TzZJ4lDUYgjMn2GijP/syqdHrlRPK3LDJMpv9hGyMZeVJsTq2KPs2gB2xbbfEhBl\n\
13GhenlekS98iJaQ88geal0e4Did36KCaLpZZ5Eeuyz1a2F1fFWHJUrExmxlddVs1jlDyusvvqfQ\n\
6PPqw87twVlErjDSuhqNfofzFeaqsE3wIIKQ8pjzkTpwLD8tlihc7mX3VblBGNszCbTtTtBO/bQb\n\
8pJfXuzglY21UZ66JO2liiXw6mbR/nth3y4od1DnxqHC15wbENNjy4VVx3h8bBt9Oits2jJ7n2bp\n\
dM5mOOwDubO03MH6pXAkkByAS2Hb8KQrUEp2e3F/gxJtkZa8LeFJxY7PThZwijkXpDEsKfStznyE\n\
m6fTmAVMdOEVAbrvBEvM9l84ZbAsyw62iipo7uWrzqZ2Q1BY0c1ghG4G5KUKO+QxV+WuVH6YXKNo\n\
CTIJ6wY4+zg1BEggIGIWzpzyimVkb7WdDRLbDULht7aDBM2sls0sVaoK1tlOrtOxAlCrFyDipnmN\n\
WOYKEF89KqvP8vm9YnDVAVqwVnIZ90ufScEhgKTieJJpiRsN6oCnuYEzwrjhYD4RHSZgmXTadgmO\n\
phdlpZ2dMkeAw43RyR6EIzKVJ7DlYNf0EP0+q3qaCZGZqjL4aIJs9cEs0VKadHR9NNRYODgLE5Fn\n\
AdJQVeusLOBusDczm1JxP7M5lSwP/38c3/tfnChW+zc9aT4hxTeRNq8pf9Os+FYOdi+CU3kpDlt5\n\
P5oN40lw5bSrFRJgUtXM7Opv6y6yDyMg9+q6niBbuke9H84mfXaokdWyhL2jo/6v7bNu5+QYOci+\n\
y0Hwnzfts3aVW/yDuAXoQB6u4XCoHF0Wg3eEzygVD2gfiJSAQ7j9jZcqEJeX1bUJLjdQQbTRRNPk\n\
BhsZzJFoWRRyJUyhbIhv36K7plTD8nCN3mjIdd0ArSsrdDom2AqkY4MMGnujO1xJ0A4vN/hCAOBN\n\
8EIeJ2F4k6a4WLMHXqsBW0iQ1I1VpQx13b003YV5b6GRqUhnuxfW7LVocBaFrkeUFoQVnLZ8CGnr\n\
mgGGGKyAgk1WsvhlG0K+s6BWXPe37kDuTbOtHP7zHISV/GZrPomK/nWSSk975JbzBzZ8gaT0k/g1\n\
ya6TiThYzKG5kgc3RQ+JIk/HxX3EkgG5UqC0zq4TSJuXG6+6B0AAR/wKJcJRjAQ7IFcO2eaos98+\n\
7rahHXnbMXjy/xD5TboABjdAVWc4WaAsSXYBokjljSZQoUAvkpy8N2BmUhHdRcmEzHlRwQAxQmtn\n\
a+v+/j68ibIRmsBG4SwutiTe+dYgH/XlD8e5+ToJsxgUETTZPSjn5tcng9/jYdESr5PURLLFyvyY\n\
q3Y9nONTdHXKcUHaWZZmtlBtFqJ091K+mhwDhUBfIdpBAO/7Puz0Pn7SqBgkxiEDHBK50zSw92np\n\
IlOOIXxNWOHqxGUfJBnrsst9d06oZXu2mIbHJ71+9/z09OSs1z6o2h7Eu5gEepYbx+I+FoBOUPA9\n\
EbpREo7G5UekM+01VoU2iu9gZULRkWbj21l6T/f6JO3HiFWOHWBYy2KCoYTCQTD0e7P5VqcRuPYC\n\
bnnS5ZdxOI3zHMiO2jj760vDYp49ff5MbD/fef7jzrMX4fb2M/g/J7wkv4kn4z657OF3FzZ2nmgO\n\
ZEYgw3MXkgw1kj/rv8IpKC+gbvhiJpIpjJABeN9HMxB96HaRG01vrjmQpxI3cVUN76nhQ5b1yMOH\n\
Xog3ateKruI6jbpN3fxf4FPimzMq8RWcSkV3PJQCbx/HkdAu9pCHeCSg5Eii2SjCIFYjmjFcOjXS\n\
/KOCahYS2/HVUhkSgHnx3AvoHj0B/YCsM7DMEim6ihkLyg/AqEFvB2EDPeXhZ+I4Alm9XZv4Z7c3\n\
izd26D1NTqnPkxvoczJRPY1BSBrAApORY5GJ9B5O5wztHvkturYym0swcnOKF1pFSZGzp5OYmRcz\n\
Nz6uT14qVkD3GiFGSwOL0mo4T4giloEG8i/eYhWnQLmzomwaksJhQxL/q6RQUQ8kqDjmImW4oV31\n\
EEdZiywOqY55wbNhAdOFomaDGwwSYxn1WGywEZlGioaj11/svLzyeThW0PRFLjQQHEJutsSPL0k0\n\
tGErU+rHH18GTY7EePHc0neqF5TKICehLrP74ZyiZTbi03sv76ImIn+5s/k6AVaKkQpyZVEXHU6i\n\
PDexI+wYl6GYTUZgwUxRRiKixpDFaIPCBsbJjizMpApI26t9MluLIMelsAv7/Wk6WkyQFtFtDnUL\n\
6x0HbZXXRA8atsjiXYYX2XXjlW/pOnamr0nnRJb0OdsxQPXIMH4mp/tlfjGNbmmIiwH9znXclblt\n\
Ruobj9GZmDZjvty9F/t8i5B3zdYAPYS1RNYWm1V3TeBZNIZR4wnGT/jCUjzzWmnso58alMzjlpj6\n\
0VILMINj5VRLld59G2HgbY6mjlnBnlSSuJCSlC82xqpHWZKj9umhFnWxNoOzYRjlccN5YsRa0VxH\n\
dJAnM7JDIzQ0hk1SYFpVDWYPiJoaEaXE2Z10E8f/nYFGiuMBPTKRQSR0mMxk4D49GSSzKMMLDDjL\n\
W/IuPKP/ol2NQ2HZ+0p6lONxW6Ab3DxL7xKyid9Il1X7Wn6G2jCe1fjRNC52bIv+E+HillPUHyNF\n\
UvoUFG6c4EiKLMCv7vCVmhGQ2ZIhhTORGJRTYKLdqfR6MBhBd8BLQF7NwnosoDdrPhQWMNDRQrKS\n\
b4mIksdG6XChD1T8YgtWgE/QKSgYWQIHj5ltKYxhiIFB3RrTsbw30IwPEPIInJ3ZMATsTTtagwTo\n\
CGPRCS4qIkCvyDQX8u6K6DUnKyEgNE1B/eHZKVDOzCh3gkzDYMuqipw49jMZ4hGOVJYhJc2YpkiE\n\
07Tbe9Ppiu7JYe/d3llbwN+nZye/dg7aB+LVe9F70xb7J6fvzzqv3/TEm5Ojg/ZZV+wdH8DT495Z\n\
59V57wQeXG7sdeFTkHLx1d7xe9H+7fSs3e2KkzPReXt61AFwAP9s77jXaXdbonO8f3R+0Dl+3RIA\n\
AtUucdR52wGlS/ROWtRt9TNxcijets/238DPvVedo07vPfV32OkdY1+H0NmeON0763X2z4/2zsTp\n\
+dkp6GACB3bQ6e4f7XXegloHvUOPov1r+7gnum/2jo6840TcnVG+agOS5KlLPcEoDzpn7f0eDsf8\n\
tQ9zB/gdtUT3tL3fwT/av7VhMHtn71sSZrf9n+fQCF6Kg723e69hbI0VUwKrsn9+1n6LOMM8dM9f\n\
dXud3nmvDRr5yQFNdLd99iswte7P4uikS7N13m23oIfeHnUMIGCq4DX8/eq826FJ6xz32mdn56e9\n\
zslxE0b+DqYFcNyDTw9odk+OaagwQydn7xEozgFNfku8e9OG52c4oTRTezgFXZix/Z7dDPqDCexZ\n\
YxTH7ddHndft4/02vj1BKO863XYT1qrTxQYd7vbdHvR5TkPGNQKs+E+LZlu0kqJzKPYOfu0g2rIx\n\
rH23I+mEpmz/jZzusCIe1xwSRhOSkrOUbeMsm1kmHDq4CiX4nr5/YelG8EufiH2z//pkf4AT16NV\n\
OWKg7xtpWFC9kOjmt0tUvrZcoTbw//YsnsA2EcM7KNFQyeQS2qfLWZTkHFEJPIg/xohLOMXinA8r\n\
AzzXfnogRMVjgJ/ADxOtTv3YAbTRBFnZNWpOYkpHQF6gZHkT3cU20hQmRrEXSaG5c0+GgTyBY+MJ\n\
M9X7G4cBGnzI2V8FhlIaFGDO8WRsdEgciZJqybQzQnU/wrumxQTUiNKsi4ZcILRPnT7AMGbiedOZ\n\
ub35fCJPe+l3iX0M0QWPpi7hAwHvsWB8OaqCD2qYCk1tY5FnhH2PTpOCAmoL3zZSV79UGnaOWY7w\n\
mE0K6/48uEnhMKP1CHicSl8NeV6B3Aqpe2HHAxA18QbsLp3cxTkd2XI2nfQxg7i4j3EJoqzgM7sl\n\
TXQ5ITmD92l2K0Z4uOUkhd/HxuMTUGRBjGz6BiWXnG2JWRmHGriYLZoyCmh0JObKBglLn9FWD9t7\n\
+/t4cF1umLWGTmaUvKTluyrz/KMxWMp+SjYtV4unO+XDNDunaOr8kfr8qpQhKxO9ldKGOElCvi7l\n\
28q0b0tTv51zHqp1UsMZhomufSlZs6v+oUg/GNwviYAl5kq0bcnhUrYiUZT/9oTi1mSukjoO6lk2\n\
n9DpI2DNj2OExQiV8iC48FRaHcsZUWfUKX14ETCipfstTP2hgPwiar6hTD7B1UWgmrJPydWqsXkv\n\
0ch/pr80ldx6qNdGdK9BDudnRxWKWIMSVOYTXnIr0KARoF0W77nRMBs01yKNr17+jKJKyjnNRO30\n\
CZ/nGwCpTVmm3eFB5cCMCo1AHbfo3BCJu2iSjCglFN0s66xQoup451nMavCe7/6yvNRLExriYDhl\n\
WXOJF/CXZjZ8DOVJRmWzG6Y+DnH/Sn5UTsDHzdbZj19FcPbfeELg3BuHn+oShzIopuEgjCsT3Yf8\n\
BIUYmaqNXrILPGfzM9dlwRpkrxFadoH/OGo3DqfAMCg1H1M+0b2mcNXxFxK0J3+FIWPxpYRXZzim\n\
NV8jsc/OEttmfTaDrj9h5v+L3EI05y2/L4R2syQ67cU5ZWS5wM0OfEOeD82W2qvNK8vdMs46vGAO\n\
ZOR/uG3ZBGXBLe9cbhTSFq9njb5wee5Yr3XMGQ0ImruRy1u4NrzN50KPLuKqr0rOEfXiouxeeuUT\n\
Hspt6tiTHlCrnpOs8vh3yHtvMrESpqydxNWGK/M5lVMmfF06Mo5JXysfmTUn0oi7u/bW9cQzaHDe\n\
iAQerEo2IBq1KbIYFYsEPYl7tea2pmfjdBd9/vPYTCPp/TPlwAhzI/3TZAQuxxsIK0UbvqHwadtl\n\
yp3s0kD6KIImKm3XVcl9EV0XWe8SQErkvci+aZ0ZKlajRTSxXRoriXqtvWR5MVoQl1DFqhk3WNfT\n\
TIgZrNWXbDAA5qA9P3cla7Tzz/nop+Sk5pmEHV/WAt8WrerAJeVXHim6jVjMlI9hpKNWMZxVXWQm\n\
aM6ZkGMQmsPzeB5h9DMaEyit131EBqc4yhO2ksgdbXpg20/4/2lCTqPlsrUgNMZKvxPAN0+JWQkY\n\
QF9GkJm2n9L/i21MjIq5Ubfpn0qOCbSV0mVh1BKDmkt+EEzpULxP6a6Qr7bUdfJaV4OVm8GoSbFE\n\
qxsOmpVcXYq3Etr1fgmkMcigaX266LTKxofKj/+ypBLePL6VmXWPrlo0zUkRzYSVuy/UWSU18mx8\n\
k8kadGZStPUC73hwBqK+kbK/O2X1iaLsz2pzSGi5jgIBODeF82Edf+H0QMcywjoakvuFvnJezPFy\n\
NbfSu1bTT9jd1GdyYB8gdsC3ZF0tuzfgg5Zg3a4/j5Is7wPTvN2tyaK4Srgvd1Xj01ubo7FMOJ7k\n\
iz45fz+d3aHFc8aB7RyZxanvEsqog+4Quy+JM+NjNh/xBSQ6OsF8kisFelfI24J7IrBJjEc7PkSy\n\
qi1rIDN00KyOFtO5rSyozpvVWHOXFNeJOseOKpPkCdhepRg5u46D+DlwFynQujw2QdbSEV/7zWd6\n\
Vkw2kMyKRIk/zmGFcZYppxE5ppAWWol828uu87qQqB3RrkbARWK2mA7g4fIAODdJcDkODPXpr0jQ\n\
Qxu9yJyJtlPqfG2ynjKYSqYomf7MhcFfkR91oIM6fw4q1hh90slo7WZ9euHiZmV2RTiydZhNo2og\n\
MvRejj8HySVBz6qmzgloGVDqeVrZ/oA8rC4X5KPjC920kVKkazzG6HBg3YVRFEuuaY/lOB0HBnxB\n\
Xlv6kx3XJ2SokJ0/BYOK3/8iII9J1GghXMqpaAICfD5R5ivRpGz6QC0gPN7jJZsRH7P4H4sEjWh4\n\
rUbR6HEerpc98pEY6U/E4yNcy/68o3jyuJTjsprAgN1+rMi+CDTpaHYdo27DmVhuSPU1MX1LEhWv\n\
TvVmqUHreB6wS8G/4mtWea1XtKPT9y9Q/nzIQ3mK9pHcMDPFL7vihccpA0/7fvEwjzl4Tz1m9zT1\n\
YoA3Ce4mkGnq8j6968szouT4LZ8OtPvAAkaiMsW+U7twwJHVcHxeox/efRzAnOlUeNIjjN3TnaAU\n\
Dd0+6QZVH3hrhMBtcZr9o7SG7wVd9Sq/XiT/jDtoepimE+1MTk4D0WQtj3OO5qMc5Yvp7Ch6oKeO\n\
qaklfSnOOy0Rg8B0EI9BIEXfXyR3bvO8ZYU+ar9YYJkYWfNK9kE/VBewM+55TTE/x0A9xunnfx8m\n\
8WRk/clQXmfzluTIJRp3mIT/ErzkEPDl1dO+6Ar99SKpXFkd773FONhAI9/XFqjAd93k+FtUhCie\n\
F3oXImRYr4/sjexJdc5Laho3628LXahupi+LbhrR6HfX+bkMiqmtMTElt2gKz8+OQPoZ7lIXi2wi\n\
XzbdQ5LfES3IVG70d6O2N2yCfQWPxQeWz+DzRzKvxecPvDst4aPplLqGHQb/CcMQ/5IQcdu8yoCZ\n\
xd8E9X2kahLBJV0b3EsED/QgA0bEyp4PsoidvGjXimRI/tCYHfxBReHQGwp2ANGMeDbIkbIqFHuQ\n\
YUxyFqOkXQg88ZAD1g/pUbcM5Y9lNS48lS+UFtUihcjNRFG9QpEjvvOk1VWJgFrslWVfTqAEf4d3\n\
C58+N703FaVE83REAYCG2euoUDhcK/BDcJf7XFt1KdsmYTfclTyfd6nWElry/V0l01XdJZDEGIdL\n\
QxSBFRwZiHoENQ9vNOuaWPyfsuWjON+nhzATN7vPtrdrP617Thk8ATVKUQw4XzjoXu2UnTU8Qw0o\n\
FhMt+5Po4SgaxJNArRVC2Vnlr4aNLjxAMN8kvmNdzwR04qpXKzB4EDMfE3D+biU6myjkWzgFV6u+\n\
eMQAaVDBnLw0D6NpMnkI57PrYNVgNhlEXjxMJAhkJ6haBF+DHC38rviEm/y2yVXR7ppEE7dA82oF\n\
1e78zJlKKHY3l8HSBeaClGIeBqSJufRADX9qLuvakmsa4skTwqSe7nWcEBwEwZc0c1NoK8GpUXtx\n\
6JoK2CtFc4KWeFINhqo6h1TSd+6BnI0MnWLC7JQb5p7p02eTEoWcN1t0EfiezqTgOL6jkiSj5Qki\n\
qHugEfzKm9FB80vD6BqGz9V5buh50fKFnBiYDHcuZAFHI2E4socKPAPR9GNV2inVBMZbRCc7FakL\n\
lhBtHQcyXjzwRrQZKWRdrI0c4ogqa6OPBV+/GfpG5PFIrlQqhHI7a3WiMR7vBk/Ixw/UjOnus0qe\n\
RvrIe5YvH31sRk8gsLTNMscuKTrVzXrZx9g4T6wbNqECvf9lvqhJD1LVkyXDhtbQLfTnNB+ifq7V\n\
3OEIpaDBQxbD6nWLbDFEUCAx9Yc3GPjM/+3PS5+HGACuYKDrFfQ1yED7dxVLN5bFsg+oZoeYRTFS\n\
XhyAS3gE0uwRw2rYgBuBaRvwtSoSTDfOyOt/9ed268Dcy76Oi7fR8KTbBeljkePxBydMly9GdoXp\n\
M1zScAWcEKOB2ShiT+dhF+2WmG35LB6/A7I5kXkSdoWNa1jXjmG8Te9iTqPSSylqp/swG1ZBeJup\n\
Obh1ujhgu7PBZtvTJj1Oi0OKjjyKo3H3YTrBginQ9uP2MwssXnWezFHjAVi1gJ1W2ofEglZu071N\n\
5l1yPilFy+T80XNv94gzzsPeMEvz/FfUzGP5wcu6Xk5hY0yI2VC7f3dNFoddmIuG3jaG9fXHyE1z\n\
9EG/aAQ3yWgUo2DLyy+eiH/fZoc/x6esn877nD6mof9y6mPopzvVbF9L6M+CFo5i5Ax4tzJ++u/L\n\
8swA1OZaeYJkTmAM3oKzcTZUJVWs3e6t8sN2/5kXnfEc9x5Nrn6WzsmDch06NJ/IcRM0/y5SBWAA\n\
uuSDjfEc5DInX1H98lSxW0Lyfry8W7NRQoUxXBMhbzFrJbNU6lljHtfczR8Pcg2fYST3Ey/Hcy3h\n\
3F6lFHf4vw8fPrjm9JaxqNJxIEUY/TB0hBn4+y30tPsMtkg03w2OsHRIrOolst+L6VSQNZeppSLp\n\
UNIXqgw1wyTAjW02wzpyTNkiGlZNk44sHXrEPgeoHD6FQNs499+ed3t9is0G4U9r208MaP5pFf5D\n\
8eHT5YZVzPuvEVepu46zX3R9Z1OhF93UMAGN7ATEAZ3KjlzfZCk7E3OI5XoTvl2PRpwdFyFGVt5H\n\
u8QAxdNx0qwRe+hiSt3Qtt9aFdEByg07YMiaCpSYBLUhDrtUOhGlx+DLCjM8hHVn+VYuQGsZJNeL\n\
dJFb+Rw4vwbdL7po9NJRas3x22hGiTXH1kUuIp/LdM7srUd+EsDAHEj/HGc9Vf19/VrZX1kaez0D\n\
vrd2ttYcbVjxxwjTCNmJoOVM2Tep7p2asyel+2/wSQI/SLLPQf22HEXXmDMEU3xW96T1MsS8qlky\n\
ig/Ms6ryr25/RskkRA4SRjCn8ovl4FVWWnzQ8H5Pf7PQADt4eIPPHAT4Prc8R5itOcYrcu1GIItg\n\
qOfSWNCHz+1ADdnscqMbq+QW7APF10Mm4fQ9Wpbvs5RyuerRcX4qU0RkgyEHrqPIWl6eazh5lulj\n\
EIE2wwK22ISt94/ITJDnwttqri8VneKnwIyxjKMjlNjraRJc2lZzmUzcW5VNijR1Bcv9BUksNwzd\n\
kywuzCLGsriTtU37pdTXbOVZt/60YyYj8Xm34k+h5kTHVQWX8A+ap7aCpgcCBW7ufirFbe5Ug0UV\n\
4M+tijO7vxyOunJCzo+Xcd8F3mIe7lRzcY5VDj9YGfYAWn4g/1P2V4tYMKU8BeoAb7HzGp3l5LrG\n\
95Mwxb9jkhl6pEpEN5ofKh4uWpfJKQlUOa9yKAQIX+IDknDzgyzxa4feh/+ULPE27azKGK+DVcqO\n\
Vbe+kJCvioexnHRP9/b/vve6Lf7efi+8BRaabnfkIuUd33Inqt1lexJTlZOE1VJ59VXK4w/WZx/s\n\
tG5GB9KkaNiXqwXh0f5fXP0VUJbNa10Q3dZWkVmqMZsvxuPk464V86u+k3CBRce3je0mlcXKc9B7\n\
ScxnSU2F5kvi9vsuWwig1+tgnRJ6qnMZLVslYIuFUblnpxN7UV06lzV6ayrWVJexrapm5ap2oK4M\n\
YVdQc7ZPnft4u5IuGmvNeEzEPCynBqYvoqu6cesT+FloHKfmI1WGW+Wt1/XMW1TsbJTQMwfj0L1g\n\
25T+13rbpmM3REgJ5XGhBbFNu44yrjPOivKTxMpO/P967wrRLPW5N+KgG63VqdoPMoyG6p8px0ud\n\
PwvZns0COQZQwlCRgpw5Xcnbof4Dms7wXujRR+ltJWrqyRPsvc6J1XxW1cfRUt7RcVTf1uFJWVqB\n\
6fz4cs1cGygzYkJAW8mYJIO1E2no1InRbfw2nuiheRyLB1ZFC8cHGYjzIL7Dje/PDqjsB07q4cC2\n\
cWgn5JoWVvJSq0rUGq1lqtM1mlbzqazxka1nrPWBTa6P+UBduT32G7YZrfENu++t0bC8AdxP/J/T\n\
5dDKVaZWtUGAj/iqmj7n8R9X80N+FYxvhYt2Bv4qKE4ys6+CZKX//3o4fE/4DeCgSvBNIN0nMwfO\n\
lX30cG57caF5MJyoI/JwsIJiXA5uPTJc3npoG5msx2leeqBYvMNl64xJy0qWl602zlU4SyS7TnqQ\n\
kinEaeckPLBPiwBECUtWkwUkKzCSmcyc4BR0L0exWGYeFdAiTEQL6rqG0zQ9fVzblZnsKkf+qAYL\n\
s6p/Unk6q6K39fnyqMGSp4M/2maV85BviNrbrRqS41yTGBhLghfqYrlrvF0q+KyszAgfGcr5ZQ0A\n\
lk+Pvy4vy6PmZp+SVNgFaTQ9/e1S/jPTf7SrFc5APP70+bNu0ZMwKy208FwZQ8sMsVmbMY5zDFxn\n\
0SgO6orPlPyKvqMkAvxJLX1VKh0zZPKZoFM9WNtPsbaC5bL1OEjvZ4Sirg3Emv+3XZAUHTu+/YJo\n\
5B+zJOajb70oa9T7qV8Iu1SYuWNx622jzmbV9huSwwxaVwdYVLsghzfUwyvLJHddqfzT36jmiL0U\n\
K+bdJNpYOuEO/VNrP1k+bpZrDFSPjCQtq+msDOElmg3Wju3P7eja6kQ1KwlnUNaXKtanzxWdNk0L\n\
Ty3i1Q9MtKgnOg8v+NB66/FUM2cfda0CHcfLjz/yVdbnNkH2ruGm6GJS2mgipgsM0UOzKxYjNJVf\n\
Z2Lrr1KD/4WDXP0HWEYyy9iqxeprNyZnB2iLcWM6bJYjN/FptSBxLVfcFGcx5VjleG0QM1XhAZ1T\n\
tw4DC8uWeFYpGutjzoooLsZX5H04kpa8av3zkcnsc7lh0RKKsRswUJZUpbcHW0MbKICSgxjsu7xh\n\
BeKr75st8ZcmimWX5K2w0SxLzrrPwOrSynFGPaDDi+xDocE+MBIN3ZtoNgNR30dZQnf0giAoh1qw\n\
vy1lGcC7dtlJbSAE7gETZm4kV9cIqvO9OtIebzbPBlVAvc708o6rJKrKT/1u9Cn6sN7G0MY0XEVD\n\
ZisrbOqTJixJnuCZ6aZwroNWLpj1KV0bxlOZLk5dKxxXBq63W4buvCpXBe69ayp68sH68oNHJ7Ku\n\
wKnbtDjmlbK+4xolPvJBwqFK13h9ziVN8hBrNjeaTR/z4/rpJmGo7M6/lhTqbOBSXe+rJU7nNsYY\n\
5mM+9YXOOaCtT6+q5lK9ClbcT3Ppa44E8uFa59ejrJXeNo41ynOB5YVWc5Xlb1sxKrshTioYy6m3\n\
XbJp766wZ1c+Nkrabs1QQzcJhHu1a4KEdi/K6/vJR0+BLPoW7GDA0IqSb4FXUpMhNACg5r0VIwSN\n\
pjfXleiYz/aDJUnTaiJiv2gJiRz/N5eREKpZvOrZ7BXcjbCeL4ZDOBvHC/IkUxV5vwvq5gyazK1L\n\
QukGC1+fUQUnJ4DXHsx/5LhyQ/RLSUduzoUxQImj2bxa9KeU2mT9mj3l3jk0GCsZ6VTsRerJoVL+\n\
TbERXJuKMmDD+lfD96hRng37pQNci8UcaqrHCD2HlmT8CBxkYSuEUPmMXYKCUTpDapxQriIL+aZ3\n\
TlywSybGgRVGo5E7irq4UAo7TLKGFybBXQz4KigqCmpWI+SYHJNIfWGSS5QJQH3QH3xyE+UEGxrC\n\
JlUYBzJ79mJgLIAyqNEZ6tJwwjrTXQmD0vLbfTbt87pESKtDGWuoAzpYGpsnrXN7BdcLiqs1Bmvt\n\
C9WNSZte0aNNYmPNE9CsaxjESmZcBdDQ7zwHrSwiWhPoB0Kfpx47cXV2XzTZPlF4dLyeKBLVsknM\n\
Avv1hnoLfzU96rTpwAKg8opyMnOscV3FgNS0STKLQa64Eiu7tLri2MwGl9NWz6midvPnoG6GbkCl\n\
k3l+a+Vl/Gfrif2ri0VEOCebPDQ4iMc2vUknqREHymNOd4yOVw7kRPj2/X/kVMSqi1Ck9GPoLHAj\n\
a46NZTEsc6TJEFXeDSJh12FUAAFZqgbM6d2t+w+aR7RXsX4oRAf2dmL5yGC9EEwTmmO1EwwMQ70O\n\
rVtxPozmZP5aTIoEV03YGVGUBoS+l04DWaJFuq6Mym+vU/Q1Stn1jUrgjJyZebJVUoqa9Sm8xNIc\n\
XlthaKxGRjacxpR+9h404uXp7RT9GIJrLksNXnfpX6rS6XrlyEY7Nanhy+OrHS8PuJrwvWJuWQJ8\n\
aQI0H8GahVBQ/+lp0mzB1Z8ybf24S3kP+q/Iy1Lk5aauCoWVm9zqusgFndlj1MpGBAYzNqWUwjS7\n\
liWyVNmsSF+fbcLSXzy7srEtfbp1n9wmW137y3yLwD1FcBrIcwdIBlQ9GyW3YbbYGqVD+QV+EN4U\n\
0wl/RW7mMHsGkxcaCDo8jmDe8go+yE5h31Dvzo+nE/SPKUwHDPYQM1l+hPWaRRNxJ8Pz+ORw55dz\n\
qZApnqJWpDWek0Jw5gI5uclsZMJXtFttkNdWIntkRG25hNuSfGL6BzEUpPjURNUqVVDUh4qgAlV2\n\
padvuUoFQMUSj7LxPxZpEVtu9b5q0pu6nJgHXAVQXVCvzgfWEnbOsC8p/u2MLGdjMbNg/cvC+oVp\n\
ygZd1ZR/WYOvkXQp7l4CbiyaO5aVvTwxFt9dqJhFNHEB/6Xbi4e8QPKE52hSNhIndyFjLgfeQj8D\n\
FZK5DrxN4mhqAtSdmORuWKRa5FMQq9BWfAO7csLVhmHU10j+JKzEectAkxd0eaz4KRVNQ2klzXEj\n\
5TJrI4Uad47a3f5B5wwz2AWEJh14nePDE/1YJ5+kp93zw8POb/QilCX55GvenjI6Evnl/2zBiQcK\n\
+lZ+g4MB/oJNfjt43ceSk/03J5QHDBhL/HEOI8Nd3FD0RsfgIHAaYzqpwAUqNQF82zvb677pv2KI\n\
JHs7H+O3RKiB+wXegqjVtMBo3WeRyDJZgBD8zWpJ7+QUZqevAMBUMGjr3eHe0dGrvf2/W6+fogyv\n\
91YDoDV1sGyUD5MkcKJzk7w/t0stt4RrSVGmiTle4UwsU8mm6MxooTmlfQSsywmhdb3a2X6v0fLG\n\
9eot5YTWyGuqMgr4sFnXFw+ktjcJ0OrPgWblw7W1bKuVmjwZY0UWPvyX6UjCoNIVeZGNKZDlcuP7\n\
90+/nz79ftT7/s3O9293vu9al1MckjJO+wC1Aco8GVTgnGlafDcMQ9iqGBsqjQ4kwcDkX26EIUg7\n\
+ljiyvR0U0rXW9j6coPEKGiGOoQBan8k3YZp8FwlmIoiy5LAIcoA1qQzgqrQjYyHtEiK37cEjKaU\n\
mDUb8opCh2zbgBa1UrVuncUT1VrPjuuQDWIwNL3cuKC9IND16QrV6A2nyQ/YhNQHumSko4pQoDvD\n\
mvaU6xcjs2FN+bvy8pNJlu2xVUCW9F2N32cxo1Fabcy1uf3T9raswoElCCR7s+/h5tYVnDvLpWu3\n\
lthOf5KpwFT3xFz7eFXFkzqiHPs0s7vkobVjO1Kr68J5iEIZqTX2whGpGYZB7JEA6hOgaU+rr6U6\n\
E5p2EF+f70Q58To0J0MH5pZzSlmau7zFrCDDxLY5TfNC4q4+0VrWDaprZhIVNnosLf01rCoWU600\n\
VWMxLWH1rWOsdOmm8AOieuaaVTWSetB4Ax4Il6PL7ytcHRpBG2cmbNrSA2p6X6tBOFOZYqUvtcwt\n\
sXRuNBHQGmEG8HWnh+919ffSPuBlhVar4STN44bLjjFtyxSnpz9PEzrS7KNsU7Tx7hUNqyrMFWux\n\
YIwrllTdgj1NWhlBEASB6r+i8D9J0zlrD7D4Jv3tJoXhqWMJ5Z8lJ+KSo/RMRqVTEOFdmqAqO0av\n\
be7ZJVa569GUvagM0u2IPTeoxcX2leeAq0wfkhlrUP3rSTqIJn1O3SGfoVuNPaMkraNi2HPUogQO\n\
jsazJpOYrL8Y6iYmJodsAgaaXRc5j800M5fCLw27sBBqCVtUatYySA3GK08rd1xtKdaawQQ1KOtr\n\
ONHRZB4bxAGZLTk+dV5G9rk6pBtIfiypgk9oak2WQqtQ8SbWmB7ePrBcbs2DGVGS0+2IRklypiRH\n\
0KXn+EmDRvNn0gXDbr/T/bX321qz4Jt6/ay1QtCszZfusB6DbSmHucwoswxN65EGs4ymVcHmr6Nq\n\
Ngookn76JxTfodGj6VWJ77aaxrW28dyWtW40EWEeYuAHgL21UVrSnFGnHn/17KO9IS7nQ45DMlxg\n\
NkG7MnX1/rUWt0YcOqe397boMSu7ZEHt5Vibydlirv7eV9JxGfQl5LZqjJvidEHXFehRDNq2qh0W\n\
RzlXYy8WA9HQ5wX+HKDWTsxK1g9rWtbz/ii+K50V5nacORyH7+fUdN0MTo/R8fqDWi2PyrlVM0Fh\n\
fHENHLtcCX2t7mulq1i/PyYZBa9sS75ZygwS/ihQCTjCYPx5lhbpMJ34Kiq7ww8NZMvAUlFaJOnD\n\
RDC9B6AGyhEhU9Ydq+I5LeLT32eB+F4QQ6X5cdWb8oHGk9HcqU/GdblxqEQG8qzeEd/nIOd8L5zZ\n\
J8VSGnL4yL6/iXVhIDSZ4OzSj1mMXh8RcCn7sAYy5LznBmKCOfDjMWaGISUaaRMBSHPONQqJnOpK\n\
FbsrKZfSyTAiNxM51BY+edc/+fvyMRteA2jNkrh22LKAkUoTNZDo4VUC5uTW1d4ADObDQ15obDr3\n\
1mhVdiJy+kvINpaZ8lGEPIBgjwW9E/uDUmBzZyxcwxUQiulvlNKcPMSyGBqeBirvFm16R4S4Sadx\n\
2R5QyFqWqEmqrE4qQdN4kdGKszW8FOQuuZMzAtekNgj+J6hQqxn3rgHhMk+2IOy64y6rRcw+oZVl\n\
O6vPeKBAetWBvuvi4BuYZViwa+Pqlt/t6oHVHHiGEvdxT2E+ZLpQsDQLEop9RFkZs/+gKyFp6fFq\n\
pxggjq3EDSkvVbr8VtHkm8rGL28i6NnKkhGby8pCWBl/NpeVh7DambZ1ea4Y0PUiUS9fw5+wydE3\n\
pATIynOEVbXQOy6lG4pfIxBmPlqucX32+aPqAXhdbZ0/kygvzmX2sN0ykH8shVGpp+LC2g639dXS\n\
mOY9JJtjUzx1Wv4iftwWT/hfz1/u6EpEzPZTvGQEzSV6cOwILp7ju93GEkxbdu+Wm9ryhL4wtWvf\n\
LXNk7L9ulr95Tt8GViTBtL5WPl+Z4XfYX6A9pM7Zi0+RvuprsBiP8S4pGo3QfyYd1374Oi6OgDyJ\n\
X7bwInca8Y9mOXEw4OYg++bd8UFLnHeOey1xdLr/rts7a4lXJydHy+5MV15G6hS0cQbb7cVz2Fo8\n\
KaF6InP2dm/gO5Ti0D39HWbwlO/DyksFE52jHZDyAb7rvnHSfyJA+TYsv6oWwIEWnaP2ySlMwfl+\n\
792qvLL2WsAZdXM/G13C5sMJdR2J4eX9IbB2fIsTXXk7R6aLb+UCVBv00mWvx4eT6DrHFkxf1QZ7\n\
swc98nxvANMaE7K40JXWNN1vo/mc6pHWQ53M8z9Os/QaabOXFJO4Fscre7IPT/pvT37F68Rn8uf+\n\
yel7+Plc/jxoH7V7+P6FfHDWlnWIXhoYh/2350e9zkG72yO7uAF32O/Cg+Oeao9Pjk/2T44PO2dv\n\
93qdk2Ns+6N6tXd0dPLu/PjgBJ7+aH3QPjs7OTvvYNvt5y89FRz7OZInOYuSlbkxSWfXfTd8Rwrg\n\
+o19ExaoUEuKkQ3KFXPlF8qH0TQUP5i3JlR/3M+TP2JOROzuG4OXSmW7bcnuh53fdohR5sAprwGv\n\
BUWFbd0gn7fPDNAEFsAxXzxzBG1mUYL6Bv78R5ylLVMSFtWddDhcZJmb6omseBJlN4lAlvXRIOIw\n\
tIYnTbIstyaNIPSVw/fks2bLzNXFyx0Td5ouCgw63PWz3IZCTrdfOqsMrCUqXynTAL0P76LJgrCw\n\
IpsCua4BSbLLeNQXJYFeflVszI5S258Ohlb0j20nBdl1qYlc3UCWLp3ptW+vOO1QBkgx5XSZA5da\n\
hMhj7Rsp+Zi4K7o5K97x5eT97CfzbVcp3Kbuyovwx/AFaqaYMSAl2gLqn6egJQ9Y+V1YsuWm4oY0\n\
XHIFvtwOmlKfnFAetHgKghEKOTO0U2F68mhYUAVUKhsouzAQI8y1zaIUR1Dm5t27NLuNMjRQmGcg\n\
uEpDq9yqKYjd/Xvs6OJKNCSCOB7yEGN1HX4R0Thg5Pf47j5VMGyM5Ww0RukCJ4MGxAHmUZFmLrAh\n\
bG6SBaVso2qty04oC6TEzXx3fNJr7xg8b9J7tS44K+imCzoH7KvsQbklA6dgaafAGmAsWtpzeR89\n\
5ChqMt8iOwZ7FWIpGKJ+ql9/H1Nm5euU6qkidqCzg9wIh96Ddd3A0Ul800Xjw3ky8wOf0Zwscs5+\n\
gCO9wGLXH6+Yy28HocXQx3T76udPvF8xyoQ20g/PyzuFRAr4XBGgFiEbDKFZ+aCXlpKpyBcsXNDu\n\
sg/L/xaec1U9VGcn/+bjuAzWJ5J49rYjjHjeV4SQ0ih0ovcyb1UZ3glM02Z6nhz/nkOHW7mHjswB\n\
3zK2CNdO4CYbs/LAw5O7ZERpStk0jSXl+cZvLkutT+HDXMW/AiC+9RNDIMNbeqk9xV4tiD/hrVc0\n\
jv8mAG+guo4YoHMZIgOPjtN5/J1gjW6USteWaII36k5KCfZGQKjoq0YtgesMQUq31Dp0J81w5h7S\n\
BVY7xXTiWHND8k5COC5AO8udLN/nOahyOlLtdGEFoWC61nsKFiBHfbnLZWIGYo1kh9XgOrNSzvRI\n\
JjekQA4nGu6fkOW6BPqvWIGwzzj/4suIvCLDtQsg5F+4wtpA9Isbe015QCg1OLLRiImngUnfkWvp\n\
YgJyKWT1ekxMSTXpR0gpZMdMqZgyFU1O7lRoB6r8cW5S+f4vZQsn9XL+MI0ncF6bvOj78iqoRSTf\n\
KeJpyxQm89VJwnJkb9HWfh1TTQ1XfuE83ljBw19kaTGID7ME49nTwe/VaG5MeYFtKNuFbBHi+Zx5\n\
cgwohKmcJxyWMMODGLdIRP18V0p15ctBYYM4iNDhogMrhx5alPWFAWFZyWm1dFb5e+QSHbwih4W/\n\
jeM5UgF6VFB1TjXNDWv6QD5EoFQ64MG6la4HPpSWnCEa0Rk5nLIO9QOkhuZ+Mrwv6fNy4y3yuQfx\n\
Ns3mN8ksEL0oA4ky/+5yo+mJBbVr1AGR1Nd7fcSGNGTgbLs3IH8wR8RNgq67f8PkXwbIFEsdYik/\n\
jOmlmxFOxKNcNizmzfVIo5lMAixo103oSouY3AfvpvlAZu2cbolGCxmqxD+5/Ab5z0wxdgqdIDAu\n\
gpgK32NwAvFc59TiC5ycikNwSnw2+OZYCAKPBqvew/IKDa45u1W2fLu2s3SC47Sd1E+yEXZ2kAyL\n\
kqO/48pfKqNcZRZTzMF7H2UzWeLBn1KVMoyiKI7/tZttin0Tt3AXZQkZF3mxowecKDw0MbIUi3zC\n\
AmScg5eyn6ifI8wEnM4xeCKUZuWAmHmuy3jy5bmdloQbgNBizUSjWdYGvSThS7dOIV+5+GDT5l9p\n\
baUH++YvSKsf+IRIMH0UpTTieA4kcbx7Ibkg9ER4moxCJr+SP2jLm9Re5xfC4HzK9iqxsu6F1VAP\n\
jfvk2KRdKu05bxyYP99KGW6FvXu+4Y6r/N32Ex2bXNjlSoLag3I26luIv40njWVVJ+nuWX5e6VrS\n\
eEMEZfajr6yRXGEbSy1VqoTDBWz1qZ7doBoN79ZaqD2YZPT72+iWaL6EhIbvzYTjpqhhi8qqNIsk\n\
1llJkWS87qpYfmByFOS5C+MKc9i3w5tGcIGF4S9nVz/8CQP3ERCWFQqvQZGeN7ZXwqQSv/wh7h8Y\n\
95QqTDcIVG3N5eByY2qvf3jbJX6P0cOUeGYW18aEM5LJToJ64wXsQGcpVBQy+iv5DzdedjraOD/U\n\
n+SpQ7memhQrXc4hSbaKjzu80PHHJgU1B1TimSe1to7vABbodv08ReUt+Zh8RcCN2E2M574q1Ek6\n\
5dp1I02Y5Btc4QXV/G+nwL9i3kuoXS1AmRxiyB0JEUEuPCIwFshiTiW5fSX5HMvjZBsLrsqe50ua\n\
OjzwZxrB0vZa4IFTMotv0IjYtJ+xONConQarjc1mgsq55MpOxGmoHo+3Eoh53wD+r4RokGy0ZwVL\n\
T+o4jVgTZg5mR6x7SnSgACIzPtG5AmIjCpnIBPfyLpw2FnLlb/kIvlAgrrQpRpUrske8mK0cM8ML\n\
5+m8sRoZNtSLysxaG5d3rKuSSOruiGhKkfaWO7hOiYYDQjKU+PgSovnyauBndp9uVl4vq/CfEcg6\n\
ak6vgD0lMXGglBztAgZEi6JWlNfOjOUzdceeA+VfvnynqFR9PwdL5QH2HvanzMHUAslsEded6Dr7\n\
IroNAuXUQ0IGonRKqjsNA8S1mytppyZ/q3ZON/kba0LZ3bJTyNRxKTNYUhKUySPgTtVd4FNTp334\n\
Bf4Ri+QsZjWHzQmkeoDmQWcil8dKijKWW1tigoXoCUy19Alpc1x26k90eSA38od8MQCltcDwqsuN\n\
8Ml/wwGmjq/LjcuNDz/X6aXiKffXsOD9QCFfIRxm4ukQ7zRR92yzZeRy4wcJuLkEJvrwkO8D6JmP\n\
aeaZDkvbQJJAdY11QNwJ0yi/reRrZpbBgsNb2Vfe+JMK3XPQX4JbFXn8m5a2bg5pyRu1MkyzKdSE\n\
0hPxFOfTSBrLZlSlEb7cAMp7CV+t1efeZGJ3az/8hn0dxHllhNwVMuyfl3e2zjDeJCA8wgZ78M3h\n\
jXr5T5vLDtV/lBRF9S8NFvSusF/9XLdhVWIVVAY/mB9P/yGejocK7+pOTcYN+9vvdmlHi+Yn5dr0\n\
+f8CoMge1g==\n\
'''\n\
allFiles = json.loads(zlib.decompress( base64.decodestring(allFiles) ))\n\
\n\
for name, text in allFiles.items():\n\
    filepath = os.path.join(scriptFolder, name)\n\
    dirname = os.path.dirname(filepath)\n\
\n\
    if not os.path.exists(dirname):\n\
        os.makedirs(dirname)\n\
\n\
    with open(filepath, 'w') as fid:\n\
        fid.write(text)\n\
\n\
\n\
def remPackage(packageName):\n\
    # Remove reference to the given `packageName`\n\
    import sys\n\
    dotName = packageName + '.'\n\
    for name in list(sys.modules.keys()):\n\
        if name.startswith(dotName):\n\
            del sys.modules[name]\n\
\n\
    if packageName in sys.modules:\n\
        del sys.modules[packageName]\n\
\n\
remPackage('mayaHooks')\n\
remPackage('mayaHooksCore')\n\
\n\
import mayaHooks.installCore\n\
import mayaHooks.selfInstaller\n\
settings = mayaHooks.installCore.loadSettings()\n\
mayaHooks.installCore.update(settings, 'mayaHooks', 'common',\n\
    utc_install_time=str(datetime.datetime.utcnow()),\n\
    utc_build_time=mayaHooks.selfInstaller.getBuildTime(),\n\
    shelf_items=[\n\
        {\n\
            'command': 'import mayaHooks;mayaHooks.main()',\n\
            'image': '',\n\
            'annotation': 'mhg'\n\
        }\n\
    ]\n\
)\n\
\n\
import mayaHooksCore\n\
mayaHooks.installCore.update(settings, 'mayaHooksCore', 'common',\n\
    utc_install_time=str(datetime.datetime.utcnow()),\n\
    utc_build_time=mayaHooksCore.getBuildTime(),\n\
)\n\
\n\
cmds.confirmDialog(m='mayaHooks successfully installed!')\n\
\n\
import inspect\n\
class FullReload(object):\n\
\n\
    @staticmethod\n\
    def cleanpath(path):\n\
        return os.path.normcase( os.path.normpath(path) )\n\
\n\
    def __call__(self, top):\n\
\n\
        self.reloaded = set()\n\
        self.src_path = os.path.dirname( self.cleanpath(top.__file__) )\n\
\n\
        self.reload_module(top)\n\
        print('done', len(self.reloaded))\n\
\n\
    def reload_module(self, top):\n\
        self.reloaded.add(top.__file__)\n\
        for name in dir(top):\n\
            sub = getattr(top, name)\n\
            if inspect.ismodule( sub ):\n\
                if hasattr(sub, '__file__') and sub.__file__ not in self.reloaded:\n\
                    try:\n\
                        if self.cleanpath(sub.__file__).startswith( self.src_path ):\n\
                            self.reload_module(sub)\n\
                    except AttributeError:\n\
                        raise\n\
        reload(top)\n\
\n\
\n\
fullReload = FullReload()\n\
\n\
import mayaHooks\n\
fullReload(mayaHooks)\n\
mayaHooks.main()\n\
\n\
");