
/*
Simplified installation of mayaHooks, just drag this into maya to start the installation.


All the code for the mayaHooks python module is compressed here with zlib
and base64.  I tried to have it all as plain text but escaping multiline code
within multiline code that contained multiline code got too complicated.
*/
python("\n\
import json\n\
import base64\n\
import datetime\n\
import os\n\
import zlib\n\
\n\
from maya import cmds\n\
\n\
try:\n\
    import mayaHooks\n\
    exists = True\n\
except:\n\
    exists = False\n\
buildTime = '2019-11-06 06:55:28.248041'\n\
if exists:\n\
    existinInfo = os.path.join(os.path.dirname( mayaHooks.__file__ ) + '-info', 'info.json')\n\
    existingBuildTime = None\n\
    if os.path.exists(existinInfo):\n\
        try:\n\
            with open(existinInfo, 'r') as fid:\n\
                data = json.load(fid)\n\
\n\
            existingBuildTime = data.get('utc_build_time', None)\n\
        except Exception:\n\
            pass\n\
\n\
    if existingBuildTime:\n\
\n\
        if buildTime > existingBuildTime:\n\
            res = cmds.confirmDialog(m='Update with this newer version of mayaHooks?\\n\\nExisting build time: {}\\nThis new build time: {}'.format(existingBuildTime, buildTime),\n\
                b=['Upgrade', 'Cancel'])\n\
            if res != 'Upgrade':\n\
                raise Exception('Canceled install')\n\
\n\
        else:\n\
            res = cmds.confirmDialog(m='Downgrade to this older version of mayaHooks?\\n\\nExisting build time: {}\\nThis old build time: {}'.format(existingBuildTime, buildTime),\n\
                b=['Downgrade', 'Cancel'])\n\
            if res != 'Downgrade':\n\
                raise Exception('Canceled install')\n\
\n\
    else:\n\
        res = cmds.confirmDialog(m='An existing mayaHooks was found but the build time could not be determined.\\n\\nUpdate to this version?    {}'.format(buildTime),\n\
            b=['Update', 'Cancel'])\n\
        if res != 'Update':\n\
            raise Exception('Canceled install')\n\
\n\
scriptFolder = os.environ['maya_app_dir'] + '/scripts'\n\
\n\
# write files to scriptFolder + '/mayaHooks'\n\
\n\
allFiles = '''eNrtfXl/20aS6FfpSJMB6dCQfEwyo4wyK0uUzTe6VqTieCX9KJAEJUQkwQFAyYrX+9lfHX0CDYqy\n\
k33vj8nuJCLQqK7urq6uqq7j09o0eojepeltvpHM8iKaTPazdHqWTcL5w9qWWBvDL5GkIpnO06wQ\n\
bx6KOO8cX2QXM/lkkl5fJ7Nr68kim0ySwUvryW/JfJxMYnyC/yOY2K+COpyOcudlqN5InHbTLK59\n\
iQj/VzJXAAAhsa3QCq/j4gD+jLNGvz+LpnG/35SNwhxexXfxpKHa7rXfnL2l1wL+UfBG8Vhki1kD\n\
htXcUi+DIFB/9qLbOBeRuE6Km8UgHAKG0LQlJsltrNsrgOrvm6KY51sbG+ajjXlUDNPsPpltjNM8\n\
Tyaqf2x+nEEHAFUUKfwB0ylwPkMPNqOoiGD4WRyNYBFhWghvG9b6PfSpliSEFvvw34Zc2AZ+32yJ\n\
IAuaIspFEU/nehDr+K9kNk5b9G9A+Aa6spYoxG478Kozw57xY6drXPOf4yxP0lnpwyi/bQgHB+Es\n\
BPU8FrO0sIE405vFxSKblT+aR8Pb6Dr+Z/xgepQEE8qfiKoojd/G1BkCEE0BtJKX8J+k0agrXzWc\n\
D+xWizmAjxsKRsvCzumyZY8rTxfZMN5GmlKP9dTgxgHimY2TbLqXREDIjel20OEuBVDVfBIX8TdB\n\
ZS41Ybt0slVuty7exoUobmKFqqAtiA+gvbUygaHkAMaMb53VwQ03igeL60ZwGg/j5C4eyR0jotEo\n\
i/PcIGktNoAJ49koR5ptBNMoL+IsBNoNmg50/Ae3x3fbItiIsuENwN+wWpeHBf3N01kewypKbhXC\n\
f9N5PNPbpYI0fhHDnI7iLfHpcxCO02waFQ0FKsQ3FtUmY+G8Et9si5ebmy7JRgng0P44jOcFLHsj\n\
gKUA2JKUYYboQ3iARAQrJdIxwmiJaAD8D0hIY0Ecx0XF3fRiP5mNRAT/wyWnBcQ9HP6aA4UjJxAA\n\
SdxJksdXFY4igeP3jWZ1RhFlarzWEuZUQbp/juA2dHd4rHzS368timF/sEgmo36RTOMLeHux9nLz\n\
xd+ev9h8/uJ7sfl66/Vftl79LfzbD3/Z3Ny8WMMvPzt9bNh7jI8tyRHpDNLDhI1SxLMi31KvNBYb\n\
G0DnsziD3TliCs+LrIGjiRGpEHCcpfcNmyktxXvztXjxw9bLza3NzfDVyx8I75b5FDHvy7k2H16s\n\
wTJ1xmIOUw1otkQ6mzwIGFd6nys2EiGd4ClQ3ESFWi6aETUm9T81O4or0RRUBn6xBht2ylh8cg6r\n\
tfkIzqDyY37FLIkx53MJaEedStZIy1/0kTwY5to0HSXjJB7hT5zsNA/xQMEDe4oT2mg2xWeYkGOc\n\
hPhjkhc57qmkCPCwVeKE2wsuiZyopy6KC+SL1hX/+ax+fLaWmxfXmkm9WPoPSa9Eev3+eAGbCUQV\n\
JehEgzydLIq4z79bYpTcJXRQALEkswI+mA2LxKyvkqvSySSmF7n1VBFCrQCX2q3zm0XBwoh8gKe6\n\
mv4vle8c9qBawXkULSZFd5gl8yI/AWIAIco6V1viPkuK+P/kOO6z3m7/zVnnYK+/197fOTvoPUn8\n\
W39E/mNApmt7Y+GxOQZmesIHoj71Hz3Vt4/gAPGKkKfMPJEpj5JhgWzeOnJRdoH9hV/zDhCjNM5n\n\
QcHbIgTxkI4PoPoHLabM42EyfiAwtixjHSR5TAcljNuDEfRTJ2cV2UPl7JXcX03BufXt5bkZxqX9\n\
XUzHnjn96oDiuMunDZ5Vtrykpgr5pMYiBGKZgjS2VZIrrGmF1urLuu7Ve98wSoefwtSmlOFNPLyV\n\
Alk8egN8peghd/sKauk41CESfTjEo5ZEJWc+6bKylognIG4gXN+Sz116hk30RVTuE9vLoAFlxMIj\n\
vntX210JfaDB3m4E7hADD2NolpdkZSlcPHt2ex9l17l3GUBfKLbEGLQ/4ksASp5LLVyemewGnsmO\n\
PCDUf6M8j7PC3ag5yb++6dC0vm1IHf6Q7LPhjMA6AcLjbBRn8WgPOEyj2ayBCkAVfBuoPUVPhqn0\n\
HjmZ5Vaaq+slqSyZq1fCcZMOfm1aeqnSwa+kOnvVIuKlNSGRFwkIf+HGuUmub2DtxASZvyUFY0va\n\
NqTYJsyPoS+9WUbAqFDjtSdAThCy7cYEuHHTZlFjPHIQEmMc4k9sVOJJ8ygraL/h+zCfTxIg7I2K\n\
PkTNzp+/uARt8x5OtKbYBnVH4x9UOBjhew7jnDXo26a4FGE0By1n1KC+nHlWSAMTGRMbhTM5HjUI\n\
iGKlFV6KsMdN8ZN4UeWfZeWml6ZA4rMHW/FIF6iVsIaZ42SN0wlQFKPeEotZNADVBOTdEeix2TSZ\n\
4Y+5XDpJXoGj6SgbBcwndkGaed5QK0DKy/h889IS5S0Ww8YNfF/hQeXRHKXWOO6jnMdiozzP0mEc\n\
jwIvNZ/BjgdOtpjvgq5WoWh7PVajIdSXkXokaVhK8wJ6yrGnPqqFoB95dGc5fHuSNH14OLFRrjRP\n\
nf3GG5PFthHsLziL0rRAMC2RLwajJNsOAi8nPcOPc3ElP7+C0dKKk2zzVhsJ6HCHV0AH8ShB3gow\n\
YR+mGTCl+5tkeKOPHNzDwFNHDOmKu78CkiZCG6YZfqdoDc4R6wgNy2NufywyZuw5GvWG8WwYt2gN\n\
cWQRyK/zRQETgKAkxIu1vyP2P238XU3BT6wDX6yFS44BSc/7DGSbZkB8J4AVwL8VJGNXGqe6pfsl\n\
fELdBZ6jWKlZrFE1DBSXKFjqD7NpkcWx3epxkA4uy6C6DX0WqpINhuhkjmz802fcYPBvSVgXa58+\n\
X6xpa0iJDrmRteNRhdlLcOKUMhNOb0f4tzFseK2kGrCyj46TkTNC+A3zAAQzRGpqyI6aPjMwzBwj\n\
5opBsMyAl5rTX9NkpqBoUpDjUZ+hVOeDIT8rT+goRpvgfy7iBR7255dle7c+vHC7AR7IbKC7BkIt\n\
n1t0HDq4YivgoOWzS7VJcgSFf1aZ0Cy+30OKL0HkNXQh8qn/5z//WeylqAgVoMfc4r9JtpwB14W9\n\
nyewU8uiMo/enDkFHIxlyFWalqhVcSZqSvcIKCCuhgArFXJPge8LgJ7FuJkV4JYG0vS1t5ZMnd+1\n\
7Q3sOVGqQt1RvcoUY1lcV2QQVndTEL5gVXMfm/DdffiwdFbcwMF1F7XAkEqVrGZNkYMndTRN77ij\n\
CpcpK7Muhypv36UqK1ligEkd7bw5aIvesdhrH7R7bVBJfFwAzyf7EH3Tfts56r87Pv4nkFGwLvj3\n\
4c6HHXrYJTpqH+1ZTfBXqYFzJCsJoz0CeXKSDu+UUnCLUjzQRQ84lVlVlOZ0o5A2hpQghou8SKdb\n\
JbmhIhHtUjMEQlZKVmDyxXxOgqR4iAtXUgMxxu6SpFm2RgY1bCae3SVZOjsPyIAKO6EPdBdcEmPM\n\
2Wy0oYeNkk4ti1wNJjJbC8FHu6meWcIBu4UAl/Tpu3iw+nfR8TW2sdILsUUfavIvXadVTu8ya64D\n\
j0YogkBfgloIIhFpwUnhqi50ktLdCu/14N5/dqrzk/TBRnBxMXPp5QZErjhDooWVs/YLLAuNEMja\n\
HPDUyPoCGiFA+K8kfOuJ3lbykd1pBfmag38CqgnbTEYkP9Pv6jUJbStoZuv1wM5LT2wGl7QINvK4\n\
eLaY0h1Fg6C7y7TO/AffAJYHBwedztERch/u0rInkKKL7exNbiah2RKNyjfN1rIvyqd9ualZh+oh\n\
omYkcQ8olI6eingFNs9sAuv6ovxqAIt0696Q7cgesRf8soiuBShTsdRSQXnI4vkkkjIFKVO2LOfF\n\
FuFYz6okc07fbUG7SxLZPhZsAGD66WWLqhK2DqDEAHb3bV7Cj2UDjR7fE8WEhDQpO24D7iyXcfbj\n\
i1esK2Kp5lMrx2IAitIspQ4A2xGJbiNAe/aAAtw1K82g2s9gEYbDZAR/RBMeCp3veDDVS73l8wjF\n\
w9P2zoHotX/puSzJf29+plV3NB7RfGXJ9U0h5KoD5nCUCpsLAruA//+QLoBRTCYkeWK7aTRboDme\n\
P0hQB4mZbPj8oOdp5iLFG1gEh2hSzBcZf3BVlQXCMLyilboqCwFXii5ACxregPZ8gnfgypYF2ukk\n\
vceJplvsQPi6J9bZfNyxYlWubjg6qLws3zH3EhWtSEkuUlzv5KfxdYJ3+PHIMkBWrSQsNJzwkV69\n\
RWooqaKpD3UDzYVh6R7yPLSBa4TlCRyP6vukO00is2iQLorG3TbtEhj1EiQ0XA8ebp/NJWryLg+F\n\
P0RfBaBQ+pcBX3qnFWcz2JYceMvt2PppLaA0C8nPhXEkgFble2lcYKkhg1b9JsqTIVp2UbUm35ut\n\
pQq4kM1qPJS8DkqPOCVZlpfdFBgOEGemDStqFUA+I21FgW36JSQ2x+JEbX36XAd2y5pwBa9V07a0\n\
S6TMVgO3oiFLlQRY7nx4G1T0KAkG5CaUXM5L1ufzzUvH/ogTZ1kftcXRWBo3+v1klhT9PhkZiUNR\n\
iyEwf4aJMv6LS58e+ah6WpEbJlF+s4uQjf2rNCFWxx5l1wawLTb9qn2UXceF6uVlRb7wIVpCziN7\n\
qHV5gON0fosKoulmlUV66rLUr4XV8WUdligRGzuU1VWzWefdKO+z+OJBo8+rDzu3B2cR+bZIc2k0\n\
+hXOV5irwrapgwhCymPOR+rAMeW0WKJwuZfdV+VKYGzPJNC2O0Fb9dNuyEt+eb6FdzDWRnnukrSX\n\
KpbAq5tF+++FfV2g/DudK4QKX3OuNEyPLRdWHePxsW100qywacuOfZKl0znb1bAP5M7SFAfrl8KR\n\
QHIALoVtlJO+PSkZ4sX9DUq0RVpyn4QnFcM8e03AKebceMawpNC3OvMRbp5OYxYw0SdXBOiPEyyx\n\
w3/hlMGyLDvYKqqguWiveo/aDUFhRb+BEfoNkNsp7JCn3H27Uvl+co2iJcgkrBvg7OPUECCBgIhZ\n\
OHPKK5aRAdX2HkhsvwaF38oeDzSzWjazVKkqWGc7uV7ECkCtXoCIm+Y1YpkrQHz1qKw+y+f3I4Or\n\
DtCC9SiXcb/0mRQcAkgqniSZlrjRQg54mis1I4wbDuYT0WEClkmnbZfgaHpRVtraKnMEONwYnexB\n\
OCJTeQJbDnZND9HvsqqnmRCZqSqDjybIVh/MEi2lSUfXR0ONhYOzMBG5CiANVbXOygJuBzszsykV\n\
9zObU8ny8P9H8b3/xbFitf/Qk+YTUnwTafOa8jfNirPkYPs8OJG33LCVd6PZMJ4El067WiEBJlXN\n\
zLb+tu5mej8Ccq+u6zGypXvU++Fs0meHGlktS9g5OOj/3D7tdo6PkIPsuhwE/3nXPm1XucW/iFuA\n\
DuThGg6HytEHMXhP+IxS8YD2gUgJOITbP3ipAnFxUV2b4GINFUQbTTRNrrGRwRyJlkUhV8IUyob4\n\
9hD9L6Ualocr9EZDrusGaF1ZodMxwVYgHRtk0NgZ3eFKgnZ4scYXAgBvgjfsOAnDmzTFxZo98FoN\n\
2EKCpG6sKmWoq+6l6TbMewuNTEU62z63Zq9Fg7ModDWitCA8wmnLh5C2rhlgiMEjULDJoyx+2YaQ\n\
7yyoFV/8jTuQe9NsI4f/vARhJb/ZmE+ion+dpNJ1Hrnl/IENXyAp/SB+TrLrZCL2FnNoruTBddFD\n\
osjTcXEfsWRAvhEorbMvBNLmxdqb7h4QwAG/QolwFCPBDsg3Q7Y56Oy2j7ptaEfucwyeHDpEfpMu\n\
gMENUNUZThYoS5JdgChSuZcJVCjQLSQndwyYmVREd1EyIXNeVDBADLna2ti4v78Pb6JshCawUTiL\n\
iw2Jd74xyEd9+cPxVr5OwiwGRQRNdg/KW/nt8eDXeFi0xNskNaFpsTI/5qpdD+f4BH2XclyQdpal\n\
mS1Um4Uo3b2UrybHQCHQV4h2EMD7vg87vY+fNCoGiXHIAIdE7jQN7E5ausiUYwjfEla4OnHZqUgG\n\
r2xz351jatmeLabh0XGv3z07OTk+7bX3qrYH8T4mgZ7lxrG4jwWgExR8T4R+kYSj8eER6Uy7gVWh\n\
jeI7WJlQdKTZ+HaW3tNFPUn7MWKVYwcYp7KYYGygcBAM/e5pvtVpBK69gFsed/llHE7jPAeyozbO\n\
/vrSOJcXzze/F5vfb/3lL1sv/xq+fP3XzdcvnHiR/CaejPvkg4ffndvYecIzkBmBDM9dSDLUSF6Y\n\
0BC8uge1vukNg0imMEYG4X0fzUD4oftFbjS9uebYnEooxGU1YqeGE1n2Iw8neiXeqX0ruorvNOq2\n\
dfN/gVOJ351Via/gVSpg46EUS/s0noSWsYc8xEMBZUcSzkYRxqUa4Yzh0rmR5h8VVLOQ2I4vl8qQ\n\
AMyrl15A9+jc5wdknYJlpkgBU8xaUIIAVg2aO4gb6PwOPxPHt8fq7dqENLu9WdyxQ+9pckp9Ht9A\n\
n5OJ6mkMYtIAFpjMHItMpPdwPmdo+chv0VuVGV2CwZhTvNIqSqqcPZ3EzryYuSFvffJTsWK0V4ga\n\
WhorlFYjdEIUsgw0kIDxHqs4AcqdFWXjkBQPG5L43ySFCmQgUcUxGCnTDe2qhzjKWmRzSHUYC54O\n\
C5guFDYb3GCQGNuox2aDjcg4UjQczf586/Wlz2mxgqYvGKGB4BBysyW+f03CoQ1bGVM/fv86aHJw\n\
xauXlsZTvaJUJjkJdZnlD+cUbbMRn987eRd1EfnLnc23CbBSDD6QK4va6HAS5bkJB2FftwwFbTID\n\
C2aKMrgQdYYsRisUNjB+c2RjJmVAWl/ts9laBDkuhV3Y70/T0WKCtIiecKhdWO84Dqu8JnrQsEUW\n\
7zO8yq4br3xLF7IzfVE6J7Kkz9mSAcpHhiExOd0w84tpdEtDXAzod65Dqcx9M1LfeIz+wbQZ8+Ue\n\
u9jnIULeNlsDNBHWE1lfbFY9MIFn0RhGjWcYEuGLNPHMa6Wxj35qUDKPW2LqR0stwAyOlRMtV3r3\n\
bYSxtDkaO2YF+1JJ4kJKUu7VGH4eZUmO+qeHWtTV2gzOhmGUxw3niRFsRXMV0UGezMgOjdDQGDZJ\n\
hWlVdZgdIGpqRJQSZ3fS8xv/dwo6KY4HNMlExoXQYTKTsfj0ZJDMogyvMOAsb8nb8Iz+i5Y1jm5l\n\
/yvpJI7HbYGOcPMsvUvIKn4jvVDti/kZ6sN4VuNH07jYsm36z4SLW06BfIwUyelTULlxgiMpsgC/\n\
usNXakZAZkuGFKFEYlBOsYZ2p9LvwWAE3QEvAYk1C+uxgN6s+VBYwEBHC8lKfk9ElDw2SocLfaDi\n\
FxuwAnyCTkHFyBI4eMxsS2EMowYM6taYjuTNgWZ8gJBH4OzMhiFgb9rRGiRARxheTnBRFQF6Raa5\n\
kLdXRK852QkBoWkKChDPToFyZkbpEGRmBVtWVeTE4ZzJEI9wpLIMKWnGNEUinKbd3rtOV3SP93vv\n\
d07bAv4+OT3+ubPX3hNvPojeu7bYPT75cNp5+64n3h0f7LVPu2LnaA+eHvVOO2/Oesfw4GJtpwuf\n\
gpSLr3aOPoj2Lyen7W5XHJ+KzuHJQQfAAfzTnaNep91tic7R7sHZXufobUsACFS8xEHnsANql+gd\n\
t6jb6mfieF8ctk9338HPnTedg07vA/W33+kdYV/70NmOONk57XV2zw52TsXJ2ekJaGECB7bX6e4e\n\
7HQOQbGD3qFH0f65fdQT3Xc7BwfecSLuzijftAFJ8tWlnmCUe53T9m4Ph2P+2oW5A/wOWqJ70t7t\n\
4B/tX9owmJ3TDy0Js9v+zzNoBC/F3s7hzlsYW+ORKYFV2T07bR8izjAP3bM33V6nd9Zrg05+vEcT\n\
3W2f/gxMrfujODju0mydddst6KG3Qx0DCJgqeA1/vznrdmjSOke99unp2Umvc3zUhJG/h2kBHHfg\n\
0z2a3eMjGirM0PHpBwSKc0CT3xLv37Xh+SlOKM3UDk5BF2Zst2c3g/5gAnvWGMVR++1B5237aLeN\n\
b48RyvtOt92Etep0sUGHu32/A32e0ZBxjQAr/tOi2RatpOjsi529nzuItmwMa9/tSDqhKdt9J6c7\n\
rIjHNYeE0YSk5Cxl2zjLZpYRhw6uQgm+Jx9eWboR/NInYt/svz5ZIODE9WhVjhjo+0aaFlQvJLr5\n\
LROVry1nqDX8vx2LJ7BVxPAOyh1UMrqE9ulyGiU5B0kCD+KPMYgSTrE458PKAM+1px4IUfEY4Cfw\n\
wwSgUz92TGw0QVZ2jZqTmNIRkBcoWd5Ed7GNNEV+UThFUmju3JORHc/g2HjGTPX+xmGABh9y91ex\n\
npTZBJhzPBkbHRJHoqRaMu6MUN2P8LZpMQE1ojTroiEXCC1UJw8wjJl42XRmbmc+n8jTXnpeYh9D\n\
dMKjqUv4QMCbLBhfjqrggxqmQlPbWOQZYd+k06SggNrCt43U1S+Vhp1j4iI8ZpPCukEPblI4zGg9\n\
Ah6n0ldDnlcgt0LqXtjxAERNvAO7Syd3cU5HtpxNJyPMIC7uY1yCKCv4zG5JI11OSM7gfZrdihEe\n\
bjlJ4fex8fkEFFkQI6u+QcklZ1tiVsahBi5mi6aMYhQdibmyQcLSZ7TVw/bO7i4eXBdrZq2hkxnl\n\
I2n5Lss8/2gMlrKfkk3L1eLpVnk/zc4oQDp/oj7/WBaQR3O3lTKBOHk/vi6L26OZ3JZmczvj1FKr\n\
ZHszDBOd+1KyZ1c9RJF+MF5fEgFLzJUA2pLLpWxFoij/7YmurUlGJXUc1LNsPqEzQsCaH8UIixEq\n\
pTZw4alMOZY7ok6SU/rwPGBESzdcmM1DAflJ1HxDyXmCy/NANWWvksvHxua9RiMPmv7S7HCroV4b\n\
pL0COZydHlQoYgVKUMlMeMmtUINGgHZZvOlGw2zQXIk0vnr5M4orKacpE7XTJ3y+bwCkNguZdogH\n\
lQOTJDQCddyie0Mk7qJJMqIsT3S3rBM9iarrnWcxq+F7vhvM8lIvzVGIg+EsZM0lfsBfmqzwKZQn\n\
GZXNbpj6OGr9K/lROaceN1tlP34Vwdl/4wmBc29cfqpLHMqwmIaDMK5MdB/yExRiZPY1eslO8Jyg\n\
z1yYBSuQvUZo2RX+06jduJwCw6Bse0z5RPeawlXHX0jQnpQUhozFlxJeneGY1nyFXD1bS2yb9QkK\n\
uv4cmP8v0gXRnLf83hDa0ZLotBfnlGTlHDc78A15PjRbaq82Ly2Hyzjr8II5kJH/4bZlE5QFt7xz\n\
uVFIW7yeNfoi4LljvdYxJykgaO5GLm/h2gA3nxM9OomrvippRNSL87KD6aVPeCi3qWNPekCtek7y\n\
mM+/Q947k4mVA2XlvKw2XJmiqZwF4esyjHFU+kopxqw5kUbc7ZW3rieiQYPzxiTwYFX+ANGozXrF\n\
qFgk6MnFqzW3FX0bp9vo9Z/HZhpJ758pF0aYG+mhJmNwOeJAWFnX8A0FUNtOU+5klwbSRxE0UZm4\n\
LksOjOi8yHqXAFIi/0X2TuvMULEaLaKJ7dRYyb1r7SXLj9GCuIQqHptxg3U9zYSYlFp9yQYDYA7a\n\
93NbskY7pZyPfkpuap5J2PLlLfBt0aoOXFJ+5ZGi24jFTHkZRjpuFQNa1UVmguacCbkGoTk8j+cR\n\
xj+jMYEydd1HZHCKozxhK4nc0aYHtv2E/5/m2DRaLlsLQmOs9DsB/O5ZLishA+jNCDLT5nP6f7GJ\n\
uU4x3ekm/VPJMoG2UrosjFpiUHPJD4IpHYr3Kd0V8tWWuk5e6WqwcjMYNSma6PGGg2Yl/ZbirYR2\n\
vV8CaQwybFqfLjpTsvGh8uO/LK2ENzVvZWbdo6sWTXNSRDNhpeMLdaJIjTwb32S6Bp1sFG29wDse\n\
nIGob6Ts705Zfe4n+7PaLBJarqNQAM5O4XxYx18448+RjLGOhuR+oa+cF3O8XM2tjK3VBBR2N/W5\n\
HNgHiF3wLVlXy+4N+KAlWLfrz6Mky/vANG+3axIjPibcl7uq8eqtTbtYJhxPPkWfnL+bzu7Q4jnj\n\
0HaOzeJsdgnl1EF3iO3XxJnxMZuP+AISHZ1gPsmVAr0r5G3BPRHYJMajHR8iWdVWKpA5OmhWR4vp\n\
3FYWVOfNarS5S4qrxJ1jR5VJ8oRsP6YYObuOw/g5dBcp0Lo8NmHW0hVfe85nelZMPpDMikWJP85h\n\
hXGWKasROaaQFlqJfdvJrvO6oKgt0a7GwEVitpgO4OHyEDg37285Egz16a9I0UMbvcicibaT6nxt\n\
up4ymEquKJnRzIXBX5EndaDDOn8MKtYYfdLJeO1mfcbg4ubRhIlwZOtAm0bVQGTovRyBDpJLgp5V\n\
TZ3mzzKg1PO0sv0BeVhdescnRxi6mSClSNd4itFhz7oLoziWXNMey3E6Egz4gry29Ocvrk/JUCE7\n\
fxIGFcH/RUCeknvRQriUJtGEBPh8osxXokkJ8oFaQHi8x0s2Iz5m8b8WCRrR8FqN4tHjPFwtIeQT\n\
MdKfiKfHuJb9eUfx5GlZxGWBgAG7/VixfRFo0tHsOkbdhnOx3JDqa6L6luQefjzZm6UGreJ5wC4F\n\
/46wecxrvaIdnXx4hfLnQx7KU7SP5Ia5KX7aFq88Thl42veLh3nM4XvqMbunqRcDvElwN4FMVJf3\n\
6V1fnhElx2/5dKDdBxYwEpX89b3ahQOOrYbj8xr98O7jAOZMJ8OTHmHsnu6EpWjo9kk3qPrAWyME\n\
bovT7B+lNXwv6KpX+fUi+SPuoOlhmk60Mzk5DUSTlTzOOZ6P0o4vprOD6IGeOqamlvSlOOuwXwA/\n\
fdmywh21JywwSYymeSOh0g8FFPbCPa8i5uQYqMc44fzv/SSejKw/GcrbbN6SPLhE1Q5b8F97l1wA\n\
vrwE2hddmr9dJJVLqqOdQ4x9DTTyfW1zCnwXTI6HRUVs4nmhdyFCbgFjZf9jT75yXkTTuFl/P+hC\n\
dbN7WZTSiEa/uu7OZVBMX42JqZtFU3h2egDyznCbulhkE/my6R6L/I5oQaZvo78btb1hE+wreCo+\n\
sHwGn9+SeS0+v+FtaQkfTafUNewp+E8YhviXhIjb5k0G7Cv+XVDfRaomoVvStcG9RPBADzJERDza\n\
814WsVsX7VqRDMkDGlN8P6i4G3pD4Q0gjBGXBslRlnZinzGMQ85ilK0LgWcc8rz6IT3pXqH8sSyp\n\
hefwudKbWqQCudknqpcmcsR3nlS6KvlPi/2w7OsIlNnv8Dbh0+em926ilC2eDiUA0DB7HVUIh2sF\n\
fgjucp9pOy5l2CTshtuSy/Mu1XpBS76/q2S3qrv2kRjjcGmIIrACIgNRj6Dm4Y1mXROL/1PKexTg\n\
+/QQZuJm+8XmZu2ndc8payegRmmJAedzB93LrWXuZVTfJ56y9kUhmLggS9bAFpzxy3P51eVjH6xb\n\
rfHSYBI9HEQDvOlAUtc4mDBPRuQpYAlUMCePyf1omkwewvnsOlgRRF48TCQI3Ogo5j/66dKpxSXZ\n\
Fp9w+902uejYXZNW6xaokYoL4LDlvvnMeUMokjaXocsFZmaUIhcGh4m59AYNf1g6MZbE0RDPnhEm\n\
9RSpY3aARQdf0sxNaK1EmkbtJZ6rtrOHiN6jLfGsGphUddSoJNPcAZkXWS3FZ9kJMMydz6fPJkEJ\n\
OVK26FLuA50WwVF8RxU/RsvTNVD3QCP4lTe/guZkhgU1DAeq86LQ86JPfjkxMBnuXMj6iObsd6QC\n\
FQQGQuPHqhxSKrmLN3reXFGIiTnzV8XEnPqOYLAySlgjdSlKRmjwyH5UMYMyImuBvDEebwfPyC8O\n\
BPXp9otKdkP6yHsaWnNrBhKbgdCXWNhlmQ+UlDnqJrDsjmv8DJ6i66u46H9r+zX5NKpqpeSp0Bq6\n\
hf6c5kNUZ7VWOByhCDF4yGJYwW6RLYYICsSN/vAG44T5v/156fMQ46UVDPRUgr4GGSjLrlbmhn5Y\n\
6rRqto9pByPl9AC4hAcgCh4wrIYNuBGYtgHfQiLBdOOMnOQf/9xuHZhrzLdxcRgNj7tdOJYXOZ5Q\n\
cAh0+R5hW5g+wyUNH4ETYvAs2xDs6dzvopkP0xOfxuP3QDbHMq3AtrBxDevaMYzD9C7mvCO9lIJc\n\
ug+zYRWEt5mag1uniz020xpsNj1t0qO02KdgwoM4GncfphMsGQJtP26+sMDizeDxHNUFgFUL2Gml\n\
XS4saOU23dtk3iVfjVJwSc4fvfR2jzjjPOwMszTPf0a1NpYfvK7r5QQ2xoSYDbX7q6vv73dhLhp6\n\
2xj21x8jR83RZfu8Edwko1GMEh8vv3gm/rrJ/nGOC1Y/nfc530pD/+UUlNBPt6rpsZbQnwUtHMXI\n\
GfAqYvz8r8sSswDU5kqJdWQSXYx1gqNuNlQ1SKzd7q1zw2bymRed8Rz3Hk2ufpbOyeFwFTo0n8hx\n\
EzT/LlIVUwC65ION8RxEJyfBT/3yVLFbQvJ+vLxbs1FChTFcESFvOWclglQqOmPi09xNuA5iCp9h\n\
JJoTL8dzLeFkWKWccPi/q6sr1/rcMgZIOg6k9KIfho4cA38fQk/bL2CLRPPt4ABrbcSqYiC7iZhO\n\
BRk/mVoqQg7lSKHaSDPMmtvYZBumI8uUzYlh1a7niLuhR4pzgMrhU8SwjXP/8Kzb61Moc5TMdOz5\n\
Myt/EP20St+h+PDpYs0qZ/33iOu0XcfZT7rCsalRi15dmK9FdgLigM79Rp5ispibCdHDgrUJX0ZH\n\
I04nixAjK1GinZOfws84y9SIHVoxB21oGz+tmuAA5Yb9FWQRAsrjgQoLRykqtYWySbBt3wwPYd1Z\n\
rogLUCwGyfUiXeRW+gNOR0HXcS4avXSUWnN8GM0oE+XYuvdE5HOZ/5id28itABiYA+mP8W1T9c9X\n\
rxb9lcWhV7N+e6tHa+XOhhV/jDDrjp05Wc6UffHoXkE5e1J6ywafJPC9JPsc1G/LUXSNKTYwJ2Z1\n\
T1ovQ0xEmiWjeM88q+rn6rJklExC5CBhBHMqv1gOXqVxxQcN7/f0NwsNsIOHN/jMQYCvP8tzhOmN\n\
Y7xR1rfusmqEei71+T58bsc1yGYXa91Y5YJglyG+WzEZmu/RLHufpZT8VI+O0zmZqhtrDDlw/SpW\n\
copcwSeyTB+DCLQZFrDFOmy9f0Vmgjz3w1ZzfQfnlP8EZoyFDB2hxF5PkxHSNjnL7NveMmZSpKkr\n\
2e2v4GF5LeieZHldFjGWhWmsbBcv5YpmQ8yqFZgdSxaJz9sV9wM1JzoMKbiAf9CCtBE0PRAoznH7\n\
UynMcasaW6kAf25VfL/99WPUfQ1yfrzJ+ibwVr9wp5qrWTzmH4O1Ufeg5RW5a7J7V8SCKYX1qwO8\n\
xb5edJaTpxdf7sEU/4o5WeiRKpLcaF5VHEK0LpNTzqRyIuJQCBC+xBWScPNKFrm1I9XDPyStuk07\n\
j6VY17EdZT+kW18ExVeFj1g+rSc7u//cedsW/2x/EN6KBM2vSOtuY1TvgEXDIE8l77wt92XaXrbX\n\
MWc4SW4tleBe5R6+sj67srOrGd1Kk7hhi652hSLDf3FdVUBZNq/1BHRbW+VbqXprvhiPk4/bVuit\n\
+k7CBdYf3zY20W9qJ89BnSbtgQVAFSAv94zfg9jqH31PB6uUslN9y5jV6r6wOCPVUXY6sdfU3T6y\n\
+G1N5ZjqKrZV9apc1fDTFRrsSmbOrqxz4m5X0jZjzRePIZmH5dSi9MVVVflBfRo9C42j1Hyk6lur\n\
/PG6UHiLio6NEnrmYBy68dnr0gtac4N07AbqKFk/LrR8t24XKMZ1xllR3opYYYn/X7MEYZXLW+VM\n\
vF12JiKrkECIWWzjpZaS2kP9BzSb4QVQs/Kx4TPbNj9q1UY7aR9XhZyaP1eFRwN7R0cq/b4uRco4\n\
C/zk+9crZrNAMRNT7tl6ySQZrJyqghITRrfxYTzRw/K47Q4shu54+ALR7cV3uKH9ufeUucFJ7RvY\n\
JhHt4lvTwkoNalVhWqG1TCS6QtNqtpIVPrLVkpU+sDfFUz5Ql2hP/YZNTCt8w85xKzQsE7/7if9z\n\
ukt6dJWpVW2I3RO+qianefrH1eyLXwXj98JFu9p+FRQnVdhXQbLS6389HL5W/B3goAbxu0C6T2YO\n\
nEv7QOXc8eJc8184KUfks2CFnLjc23pkOLz10LZJWY/TvPRAsXeHy9bZnpaVBK8kULc9dlnS2HaS\n\
b5QsJ047J52AfVoEICJYMpgs0FiBkcxkXgKnYHo5RsSyCqlwEWHiRVA1Npym6enj2lZM7CpC/pgB\n\
C7Oqo1J5OqsitfX58pi8kp+DP5blMXcg3xC1Z1lV93JuVQyMJaEBdZHSNf4rFXwerXwIHxnK+WkF\n\
AJaXjr/uLQdNG0cASgFhF3zR9PSPC/nPTP/RrlYQA7H30+fPukVPwqy00EJxZQwtM8RmbT42juC/\n\
zqJRHNQVdyl5Cn1DIfr8SS19VSvbE2RysaBTPVjZJ7C2QuSy9dhL72eEoq69wwr977sgKfqB/P4L\n\
opF/ypKYj37vRVmhnk79QtiluMyVjFvPGs0gVu28IfnXoDF2gEWrC3JhQ/26skxy15XKK/2DanrY\n\
S/HIvJs0Fksn3KF/au0ny6fNco3d6YlxmmX1m5UhvHOzwdqR87kdu1qdqGYlnQvK+lLF+vS5otOm\n\
aeGp9fv4AxOL6Yl9w/tANPZ6fNrM2UddqzDC8fLjDzOCmXObIHvXcF10MeVrNBHTBQbAoZUWi/2Z\n\
yqozsfF3qcH/xCGk/gMsI5llbNU69bUbk28EtMWoLB2UynGR+LRa8LeWK66L05gymHI0NIiZKq2/\n\
zlhbh4GFZUu8qBRl9TFnRRTn40vyUxxJC121vvjI5M25WLNoCcXYNRgoS6rSOYSNnA0UQMmfDPZd\n\
3rDC3NX3zZb4WxPFsgtyblhrliVn3WdgdWllEKMe0D9G9qHQYJcZiYbuTTSbgajvoyyhO3pBEJTD\n\
GtiDlmL48WpedlIbdIB7wARxG8nVNW7qbKqOtMebzbNBFdBKwkPrSqwkqspP/f70KRZEuo2hjWn4\n\
GA2ZraywqU9JsCQ1gWemm8K5PXp0waxP6ZYxnspkbOoW4qgycL3dsngcZyoTBO69ayopcmV9eeXR\n\
iawbc+o2LY54pazvuAKIj3wodEVetPuYHdcjN+k3JXj/2lHgsARGRbIvl/iM2+gtQ8IBan10WbWK\n\
6sm2QmmaS19zcI0PyzpvH2WQ9LZxjE6eay0vtJoLLn/bioXajRpS8U1/lH26Zqihm0mh3nJdF5L5\n\
RQOmxfvfHDQhtOpQ/dKskWDzxXAIB8Z4Qd5YqgzsN0FthIh0HoX2p1QmyIkZtdH/jxyDhYbozZGO\n\
3MD+MUCJo9m8WlmmlD9j9cIw5d45GhXL5eh830XqSdRR/k1RBVwAidIsw4pXI8aoUZ4N+6VzTEuH\n\
HN2oxwg9h5aA+AQcZPUkhFD5jB1pglE6Q/qbUEIcC/mmd05csEsmxoEVRqORO4q6UESKdEuyhhcm\n\
wV0M+EYkKgpqVnPWm0SGmAgnTHKJMgGoD4KDT26inGBDQ9iWCuNApmheDIwhTMY8OkNdGl5XZ8Eq\n\
YVBafrvPpn2MlQjp8dC+GuqADpYGnUkj1U7BRWniaiG7WjW7ujFp0yt6tElsrHkCWjcNg3iU/VYB\n\
NPQ7z0EkK1XW8CeQfTxlv4mPs9OfSSmJMpTjK0SBjZZqPgvs12vqLfzV9GiVpgMLgEpeyRmzsZRy\n\
FQPSVibJLIZz91I82qXVFQcdNrhqs3pOhZubPwZ1M3QDmo1MJlsrNuI/G8/sX12sVMGJv+QxwaEv\n\
tgVKuhaNODYbE4djQLZyuybCJ5HSBhAuq3ynq3Sj4/SNLGw1lhWXzCEmYy95N4iEHW5RDwJkqegs\n\
5xC3rgFoHtFsw2qSEB3Y24nlApJQyXsU3WEtMJwK1Rs08sT5MJqTFWgxKRJcNWGn3VCKAHosOg1k\n\
HRDpmTEqv71O0ZMmZYcxqrMycmbm2UZJN2jW54kSSxNFbYShMZ4Y2WkaU47Te1AMl+dQU/RjCK65\n\
LP903d13qRSk63QiG23V5B8vj692vDzgalbxitVhCfClWbZ8BGsWQkH9w3NxLXcLWz1SUV4F/jtW\n\
sRSruK7LDmFpILd8K3JAZ/YYtbIezWDGplZPmGbXsgaTqssU6RukdVj28xeXNralTzfuk9tko2t/\n\
mW8QuOcITgN56QDJgKJno+Q2zBYbo3Qov8APwptiOuGvyDEbZs9g8koDQVe+EcxbXsEHWSnsGerd\n\
+fF8gi4ihemAwe5jqsSPsF6zaCLuZEAbnxru/HLqDrJGU5yHNEhzggQOx5eTm8xGJuBDO6IGeW2p\n\
qyfGoJZrhC1JWKV/EDNBik9NHKpS/ER9cAUqT2Xnc/qWyyAAVKwhKBv/a5EWseWI7itXvK7rVXnA\n\
VQDVhcHqhFMtYSel+pLq0s7IcraXMvvVvyysX5mmbNNUTfmXNfgaKZeC1CXgxqK5ZRmayxNj8dyF\n\
ivJD2w/wXjLgP+QFkic8R6uqkTa5CxmlOPBWkhmoIMZV4K0TR1MToK6FJHfDKsgin4JIhebSG9iV\n\
Ey5nC6O+RvInQSXOWwaavKPKY8VPqSoXSippjhspl2kBKTi3c9Du9vc6p5giLSA06bDrHO0f68c6\n\
uyE97Z7t73d+oRehrPkmX/P2lPGEyC//ZwNOO1DON/IbHAzwF2zyy97bPtY07L87prRTwFjij3MY\n\
Ge7ihqI3OgIHgdMYsxcFLlCpBeDb3ulO913/DUMkudv5GL8lQg3cL/AiQK2mBUbrPYtE1mEChOBv\n\
Vkl6xycwO30FAKaCQVvv9ncODt7s7P7Tev0c5Xe9txoAranDS6N8mCSBE8+a5P25Xcu3JVwrijJL\n\
zPEWY2KZSdZFZ0YLzTnTI2BdTtCp66/NJmyNljcSVm8pJxhF3tSUUcCHzbq+eCC1vUmAVn8ONCvh\n\
qq1hW63U5MmoJLLn4b9MRxIG1UbIi2xMoR8Xa99+eP7t9Pm3o96377a+Pdz6tmvdz3AQxzjtA9QG\n\
KPJkTIFzpmnx3TAMYatiNKU0OJAEA5N/sRaGIO3oY4lLn9NlId3wYOuLNRKjoBnqDwao/ZH0mqXB\n\
cxlaqrora86GKANYk84IqkoqMoLQIil+3xIwmlLmz2zIKwodsl0DWtRK1Lp1Fk9Uaz07bjQQiMDQ\n\
9GLtnPaCQO+fS1Sh15wm32ETUh3ono2OKkKBrs1q2lMyWYxlhjXl78rLTwZYtr5WAVmSdzXincWM\n\
Rmm1MZnj5g+bm7LMA+a4l+zNvoqaW7dQ7iyXbp5aYjP9QWaeUt0Tc+3jbQ1P6oiSuNPMbpOT0pbt\n\
S6xuzOYhCmWk0tgLR6RmGAaxRwKoT4CmPa2+lupMaNphb32+FuTM3tCcjByYysyplWiusxazgowS\n\
m+Y0zQuJu/pEa1g3qKqZSVTY6LG09Newqlits9JUjcW0hNW3jrFmKR2MxA+I6oVrUtVI6kHjJXAg\n\
XI4uv69wdWgEbZyZsGlLD6jpfa0G4UxliqWk1DK3xNK50URAa4QppledHr7a1N9L24CXFVqthpM0\n\
jxsuO8ZEJ1Ocnv48TehIs4+yddHG60c0qqrAUCz2gVGhWLNzA/Y0aWUEQRAEKjCKwv8kTeesPcDi\n\
m/yq6xS4po4llH+WnIhLjtJTGcdNYXd3aYKq7Bgdl7lnl1jlrkcz9qIySLcjdl6gFuebl54DrjJ9\n\
SGasQfWvJ+kgmvQ52YV8hp4l9oyStI6KYc9RixI4OBovmkxissBfqJuYoulkEzDQ7MK7eWymmbkU\n\
fmnYhYVQS9iiUrOWQWowXnlaeaRqK7HWDCaoQVlfw4mO5vLYIA7IbMjxqfMyss/VISW848eSKviE\n\
ptZkJbQq4a5jEePh7QPL5dY8mBElOd2MaJQkZ0pyBF16jp80aDR/Jl0w7PY73Z97v6w0C76p189a\n\
jwiatQm5HdZjsC0lyZY5WJahaT3SYJbRtKoI/HVUzUYBRdLP/4TiOzR6Mr0q8d1W07iYM57bspiK\n\
JiJMewv8ALC3NkpLmjPq1OOvnn20N8Tl9LtxSIYLTJFnlz6u3r3W4taIQ+f09t4UPWVllyyovRwr\n\
MzlbzNXf+2oGLoO+hNweG+O6OFnQVQU61YK2rYpTxVHO5b6LxUA09HmBPweotROzkgWqmpblvD+K\n\
70pnhbkZZw7HAe85NV0159FTdLz+oFbLo3ph1dxJGDpbA8euh0Ffq7ta6S3V749JRsHr2pJ7kjKD\n\
hN8LVAIOMHx9nqVFOkwnvpK97vBDA9kysFSUFkn6MBFM7wGogXJEyJR1x6o6S4v49LdZIL4VxFBp\n\
flz1pnyg8WQ0t+rTV12s7SuRgZyLt8S3Ocg53wpn9kmxlIYcPrLvb2JdeYZqxd9EXKJmFqOPRwRc\n\
yj6sqZI8JicwEBNMsh6PMZcKKdGy2ruQ5pxrFBI5OZSqplZSLqWfXUROJXKoLXzyvn/8z+VjrpRf\n\
rxu2rJCjEisNJHp4lYApoHU5MVmDHnmhsencW6NV+XzI7y0h21hm6hMR8gCCvRX0TuwPSnHCnbFw\n\
DVdAKKa/UUpz8hDLalt4GqhMVbTpHRHiJp3GZXtAIYsloiap8iCplEbjRUYrztbwUvy25E7OCFyT\n\
2iD4n6BCrWbc2waEyzzZgrDtjrusFjH7hFaW7aw+ll+B9KoDfde9wTcwy7BgF1/VLb/Z1gOrOfAM\n\
Je7insIkv3ShYGkWJBT7iLIyZv9BV0LS0uPVTjFAHFuJG1FdKqX4ewVTrysbv7yJoGePVihYX1aF\n\
wMqRs76sGoHVzrStywzFgK4XiXr5Fv6ETY5+ISVAVmYgLNuEvnAp3VD8HIEw89FyhOuzhx8lq8er\n\
auv8mUR5cSbzbW2XgfxrKYxKwQ4X1ma4qa+WxjTvIdkcm+K50/In8f2meMb/evl6S5e6Ybaf4iUj\n\
aC7Rg2NHcPEc3203lmDasnu3XNSWp8GFqV35bpmDQ/99s/y7Z8FtYAEMTIRrZcCVOXGH/QXaQ+oc\n\
vfgU6au+BovxGO+SotEIfWfSce2Hb+PiAMiT+GULL3KnEf9ollPtAm4Osu/eH+21xFnnqNcSBye7\n\
77u905Z4c3x8sOzO9NHLSJ20Nc5gu716CVuLJyVUT2SW2+4NfIdSHLpuv8ecl/J9WHmpYGLCdgek\n\
fIDvuu+chJkIUL4Ny6+q9VagReegfXwCU3C223v/WCZWey3gjLq5n40uYPPhhLpuw/Dyfh9YO77F\n\
ia68nSPTxbdyAaoNeumy1+P9SXSdYwumr2qDndmDHnm+M4BpjQlZXOhKa5ruw2g+p4KX9VAn8/y3\n\
kyy9RtrsJcUkrsXx0p7s/eP+4fHPeJ34Qv7cPT75AD9fyp977YN2D9+/kg9O27LszWsDY79/eHbQ\n\
6+y1uz2yixtw+/0uPDjqqfb45Oh49/hov3N6uNPrHB9h2+/Vq52Dg+P3Z0d7x/D0e+uD9unp8elZ\n\
B9tuvnztKRHYz5E8yVGUrMyNSTq77rsRLFIA12/sm7BARRtSmGhQLskqv1D+i6ah+M68NdHq436e\n\
/BZz6l533xi8VPLXTUt23+/8skWMMgdOeQ14LSgwauMG+bx9ZoAmsACO+eqFI2gzixLUN/Dn3+Is\n\
bZmao6jupMPhIsvcLEZkxZMou3H0WdZHg4jD0BqexMKynpc0gtBXDt+Tz5otM1fnr7dM6GW6KDDu\n\
btvPchsKOd1+6awysJaofKVMA/Q+vIsmC8LCCu4J5LoGJMku41FflDZ5+VWxMTtKbX86GFqRMbad\n\
FGTXpSZydQNZunSm17694rRDGSDFJM1lDlxqESKPtW+k5GPirujirHjHl5P3ix/Mt12lcJtiIq/C\n\
78NXqJli0HxKtAXUP09BSx6w8ruwZMt1xQ1puOQGfLEZNKU+OaEUX/EUBCMUcmZop8KE3tGwoBKb\n\
VJdOdmEgRpidmkUpDiLMzbv3aXYbZWigMM9AcJWGVrlVUxC7+/fY0fmlaEgEcTzkIcbqOvwionHA\n\
yO/x3X2qYNgYy9lojNIFTgYNiGOsoyLNXGBD2NwkC0rZRhXzlp1Q3kSJm/nu6LjX3jJ43qT3al1w\n\
VtBFF3QO2FfZg3JJBk7B0k6BJadYtLTn8j56yFHUZL5Fdgz2KsT6JkT9VCD9PqZcxNcpFexE7EBn\n\
B7kRDr0H67qBY5H4povGh/Nk5gc+ozlZ5JwAAEd6jtWUP14yl98MQouhj+n21c+feL9ihAltpO9e\n\
lncKiRTwuSJALUI2GEKz8kEvLeUTkS9YuKDdZR+W/y0856p6qM5O/s3HcRmsTyTx7G1HGPG8rwgh\n\
pVHo1Ohl3qpyohOYps30PFnxPYcOt3IPHZk1vWVsEa6dwM23ZWVOhyd3yYgSe7JpGmuW843fXNby\n\
nsKHuQoBBUB86yeGQIa39FJ7ir1ZEH/CW69oHP9DAN5AdR0xQOcyRAYeHaXz+BvBGt0ola4t0QRv\n\
1J2sCuyNgFDRV41aAtcZgpRuqXXoTprhzD2kCyyniQm4sUqF5J2EcFyAdpY7ebHPclDldJTaycIK\n\
QMEEp/cUKEBO+nKXy9wExBrJDqvBdWalLONA77wPMYjDiYT7A/JCl0D/HQve9Rnnn3w5hB/JCe0C\n\
CPkXrrA2EP3khh9TKgxKpo1sNGLiaWCadORaOv2+XApZHh1zLlLR8xFSCtkxU6rWS1V5kzsV1oEq\n\
f5yb5Lf/S/m1Sb2cP0zjCZzXJpP4rrwKahHJd4p42jLVtnzVhbDG1iHa2q9jqkLhyi+c+RprXvhL\n\
Ey0G8X6WYEh3Ovi1GuCMWR+wDSV8kC1CPJ8zT5i9QpiqR8JhCTM8iHGLRNTPN6VsT740DDaIvQgd\n\
LjqwcuihRYlPGBBWMZxWa0eVv0cu0cErclj42zieIxWgRwUVg1TT3LCmD+RDBErJ9h+sW+l64ENp\n\
yRmiEZ2RwynrUD9AamjuJ8P7kj4v1g6Rzz2IwzSb3ySzQPSiDCTK/JuLtaYnDtQuvAZEUl9e9Akb\n\
0pCBs+3egfzBHBE3Cbru/gPzXxkgU6z7h/XpMIKXbkY4F41y2bCYN5e/jGYyv62gXTehKy1iclfe\n\
TXNFZu2cbolGCxmmxD+5YAX5z0wxbgqdIDAugpgK32Nwyu1cp5XiC5ycyilwEnk2+OZYOgGPBqtC\n\
wvKaBq45u1W2fLu2s3SC47Sd1I+zEXa2lwyLkqO/48pfqtpbZRZTTC97H2UzWRTBn1GUkmyiKI7/\n\
tZuti10Tt3AXZQkZF3mxowecKDw0MaoUa0rCAmScXpYSgKifI0xym84xeCKUZuWAmHkeqGhXvjy3\n\
M3NwAxBarJloNMvaoJckfAnKKdwrF1c2bf6d1lZ6sK//hLR6xSdEghmUKKsPx3MgiePdC8kFoSe6\n\
0yTVMSmG/AFb3jTwOsUOhuJTwlOJlXUvrIa6b9wnxybzUGnPeWPA/ClHynAr7N3zDXdc5e+2n+jY\n\
pHkul93THpSzUd9C/DCeNJaVUqS7Z/l5pWtJ4w0RlNmPvrJGcoVtLLVUqRIOF7DVp3p2g2okvFud\n\
oPZgkpHvh9Et0XwJCQ3fmwzGzdLCFpXHMg2SWGflBZKxuo/F8QOTowDPbRhXmMO+Hd40gnOsQ34x\n\
u/zuTxi0j4CwEE94DYr0vLH5KEyqKMsf4v6BcU+poHGDQNWW+A0u1qb2+oe3XeL3GDkMYPDj2nhw\n\
RjLZSlBvPIcd6CyFikBGfyX/4cbLTkcbp0j6kzx1KN1Rk+Kky2kUyVbxcYsXOv7YpIDmgCoK86TW\n\
FrUdwALdrp6qp7wln5KyB7gRu4nx3FeFOkmnXO1tpAmTfIMrvKCaAu0E+FfMewm1qwUok0MMuSMh\n\
IsiFRwTGklLMqSS3r+RfY3mcbGOlAsTLmzo88EcawdL2WuCBUzKLb9CI2LSfsTjQqJ0Gq43NZoLK\n\
ueTKTsRpqIKNt3aGed8A/q+EaJBstGcFS0/qOI1YE2YOZkere4paoAAikx7RuQJiIwqZyAR38i6c\n\
NhZy5W/5CD5XIC61KUYV+LFHvJg9OmaGF87TeeNxZNhQLyoza21c3rGuSiKpuyOiKUXZW+7gOisY\n\
DgjJUOLjywnmy6mBn9l9uolpvazCf0Yg66g5vQL2lMTceVJytHPzEy2KWlFeOzOWz9Qtew6Uf/ny\n\
naKy1f0YLJUH2HvYny4H0woks0W8rPr8WGIyAcqph4QMROmUVEwZBohrN1fSTk0KU+2cblIY1oSx\n\
u4WakKnjUmawpCQok0fAnaqywKemTvnwE/wjFslpzGoOmxNI9QDNg85ELiiVFGUsNzbEBGuaE5hq\n\
VQ/S5rhQ05/o8kBu5Kt8MQCltcDwqou18Nl/wwGmjq+LtYu1qx/r9FLxnPtrWPC+o5CvEA4z8XyI\n\
d5qoe7bZMnKx9p0E3FwCE314yPcB9MynNPNMh6VtIEmgusY6IO6EaZTfVlIWM8tgweFQ9pU3/qRC\n\
9xz0l+BWRR7/pqWtm0Na8katDNNsCjWh9EQ8x/k0ksayGVWZdC/WgPJew1cr9bkzmdjd2g9/x772\n\
4rwyQu4KGfaPyztbZRjvEhAeYYM9+ObwRr38w+ayQxUTJUVRxUiDBb0r7Fc/1m1YlVQFlcEr8+P5\n\
v8Tz8VDhXd2pybhhf/vNNu1o0fykXJs+/1+0AJkT\n\
'''\n\
allFiles = json.loads(zlib.decompress( base64.decodestring(allFiles) ))\n\
\n\
for name, text in allFiles.items():\n\
    filepath = os.path.join(scriptFolder, name)\n\
    dirname = os.path.dirname(filepath)\n\
\n\
    if not os.path.exists(dirname):\n\
        os.makedirs(dirname)\n\
\n\
    with open(filepath, 'w') as fid:\n\
        fid.write(text)\n\
\n\
\n\
def remPackage(packageName):\n\
    # Remove reference to the given `packageName`\n\
    import sys\n\
    dotName = packageName + '.'\n\
    for name in sys.path:\n\
        if name.startswith(dotName):\n\
            del sys.path[name]\n\
\n\
    if packageName in sys.path:\n\
        del sys.path[packageName]\n\
\n\
remPackage('mayaHooks')\n\
remPackage('mayaHooksCore')\n\
\n\
import mayaHooks.installCore\n\
import mayaHooks.selfInstaller\n\
settings = mayaHooks.installCore.loadSettings()\n\
mayaHooks.installCore.update(settings, 'mayaHooks', 'common',\n\
    utc_install_time=str(datetime.datetime.utcnow()),\n\
    utc_build_time=mayaHooks.selfInstaller.getBuildTime(),\n\
)\n\
\n\
import mayaHooksCore\n\
mayaHooks.installCore.update(settings, 'mayaHooksCore', 'common',\n\
    utc_install_time=str(datetime.datetime.utcnow()),\n\
    utc_build_time=mayaHooksCore.getBuildTime(),\n\
)\n\
\n\
cmds.confirmDialog(m='mayaHooks successfully installed!')\n\
\n\
\n\
class FullReload(object):\n\
\n\
    @staticmethod\n\
    def cleanpath(path):\n\
        return os.path.normcase( os.path.normpath(path) )\n\
\n\
    def __call__(self, top):\n\
\n\
        self.reloaded = set()\n\
        self.src_path = os.path.dirname( self.cleanpath(top.__file__) )\n\
\n\
        self.reload_module(top)\n\
        print('done', len(self.reloaded))\n\
\n\
    def reload_module(self, top):\n\
        self.reloaded.add(top.__file__)\n\
        for name in dir(top):\n\
            sub = getattr(top, name)\n\
            if inspect.ismodule( sub ):\n\
                if hasattr(sub, '__file__') and sub.__file__ not in self.reloaded:\n\
                    try:\n\
                        if self.cleanpath(sub.__file__).startswith( self.src_path ):\n\
                            self.reload_module(sub)\n\
                    except AttributeError:\n\
                        raise\n\
        reload(top)\n\
\n\
\n\
fullReload = FullReload()\n\
\n\
import mayaHooks\n\
fullReload(mayaHooks)\n\
mayaHooks.main()\n\
\n\
");