
/*
Simplified installation of mayaHooks, just drag this into maya to start the installation.


All the code for the mayaHooks python module is compressed here with zlib
and base64.  I tried to have it all as plain text but escaping multiline code
within multiline code that contained multiline code got too complicated.
*/
python("\n\
import json\n\
import base64\n\
import datetime\n\
import os\n\
import zlib\n\
\n\
from maya import cmds\n\
\n\
try:\n\
    import mayaHooks\n\
    exists = True\n\
except:\n\
    exists = False\n\
buildTime = '2020-06-24 06:42:41.889420'\n\
if exists:\n\
    existinInfo = os.path.join(os.path.dirname( mayaHooks.__file__ ) + '-info', 'info.json')\n\
    existingBuildTime = None\n\
    if os.path.exists(existinInfo):\n\
        try:\n\
            with open(existinInfo, 'r') as fid:\n\
                data = json.load(fid)\n\
\n\
            existingBuildTime = data.get('utc_build_time', None)\n\
        except Exception:\n\
            pass\n\
\n\
    if existingBuildTime:\n\
\n\
        if buildTime > existingBuildTime:\n\
            res = cmds.confirmDialog(m='Update with this newer version of mayaHooks?\\n\\nExisting build time: {}\\nThis new build time: {}'.format(existingBuildTime, buildTime),\n\
                b=['Upgrade', 'Cancel'])\n\
            if res != 'Upgrade':\n\
                raise Exception('Canceled install')\n\
\n\
        else:\n\
            res = cmds.confirmDialog(m='Downgrade to this older version of mayaHooks?\\n\\nExisting build time: {}\\nThis old build time: {}'.format(existingBuildTime, buildTime),\n\
                b=['Downgrade', 'Cancel'])\n\
            if res != 'Downgrade':\n\
                raise Exception('Canceled install')\n\
\n\
    else:\n\
        res = cmds.confirmDialog(m='An existing mayaHooks was found but the build time could not be determined.\\n\\nUpdate to this version?    {}'.format(buildTime),\n\
            b=['Update', 'Cancel'])\n\
        if res != 'Update':\n\
            raise Exception('Canceled install')\n\
\n\
scriptFolder = os.environ['maya_app_dir'] + '/scripts'\n\
\n\
# write files to scriptFolder + '/mayaHooks'\n\
\n\
allFiles = '''eNrtff1fG0eS97/Si5OdmUSWsZ3L7pKQPQzC1i0GDok4WeAjBmkEEySNMjMCsz4/f/tTL/060yMJ\n\
27m7H86btWGmp1+rq6uqq771YWMaP8Rvsuy22M3y5Gk6G2fP8K/2b0U229gSGx/O8/OZgD/nG4ty\n\
OLhapJPRoEynyTm8Pd94sfn8b0+fbz59/r3Y/G7ru3/bevm39t/+8m+bm5vnG/jlx42WMG1A1UUZ\n\
TybYVnv+gPUHQYDl8P+6XTHMZmUyK4st9Ur34tkz8TqZJXlcJiMxzrOpKMo8FCP4HTvVhj7Osvsw\n\
EtF6/d78Tjz/y9aLza3NzfbLF3+hfrfMp9jzwV2SF2k2Mx+eb4gnojsW8zwpoJstkc0mDwLGld0X\n\
Qg4xLuETUWaivIlLoarAGVFjUv9Xs9NLyjKdXRc0BbWBn28Ms+mUe6Ef8ov5KJ3UHvOrIlvkQznk\n\
WCzyichy8a90LsbpJLFGWv1iABMac50b02yUjtNkhL/iZGdFex6XN+3rpJzihIZRJD7ChBzhJCTv\n\
06KESRiLtAwKEXNDtVZwSeREPXZR3Eo+aV3xz0f1y0druXlxrZnUi6V/kPRKpDcYjBflIk8GA5FO\n\
51leiviqyCaLMhnw7y0xSu9SXPkWEEs6K+GD2bBMzfrK74bZZJLQi8J6qghB/jrJrq+BQKwnmV26\n\
uFmUQAjmQZlM52r65SNYevVEjwLpT/V/OB0VtZeaPahSo2QcLyZlb5in87I4BmJoQefikaLglrjP\n\
0zL5jwLHfdrfHbw67R7sDfY6+zunB31VPwxHbKtBITUdwI9JHg4Gs3gKc0o7+Am8bxfwLrlLJqEq\n\
vNd5dfo6MhWZpu2NBd0E8puNjuPhbXydqCJhobs55zf/SB5aNNKfeZtuH2azJNpSRCCXHH88SWC9\n\
YVvfJLCyQ1iAMf1s6sH9hV/zDhCjLClmQcnboi3E0RzXGKj+QdVYzJNhOn6gaqwuEBtJ4hG2UCRx\n\
PrzBcXt6BO1Yn23ZJF7mD1vVXZPzANQUnFnfXpyZYVzY3yXvh8m8FB36p9qIVSmOW+8l+e8Y5sNq\n\
Q0858kndizYQy7QII6diGJg1rVBafdnUvHrvG4b6t9JTm1KGN8nwtss8KRm9Ar5S9pG7fQa1dB3q\n\
EKk+HJJRS3alYD7psrKWSCZFQr30LfncpWfYRJ9E5VF1csyM66qhy9gLZ8qXrLa7EvpAg70dBu4Q\n\
Aw9jiKpLspjjub56JC3xzTe393F+XXiXoUyKckuM49uE+BJUJc+lFi7PTDYDz2RDnirUv3FRJMAA\n\
nY1aiFlWeqdD0/q2IXX4QbLP0BmBdQK0j/JRkiejPeAwcLg21AqVqvrtSu0penSdbTnjcjKrpTRX\n\
10tSW7IceFYX5Lju7J/pPITjJrv6zSzKE9GHVUCx4BJe78MSXLaIeGlNZiNJQPgbbpyb9PoG1k5M\n\
kPkLIx5iSdo2KIcga8DC0JbeLCNgVDcwQfYEyAlCth1OgBtHNosa45GDNXGP2/grFqrwpHmcl7Tf\n\
8H27mE9SIOxnQVTjW1Ds7OnzizZIhHCiRWJ7WwS6/0GNg1F/z2Ccs5C+jcSFaMfzeTIbhdSWM8+q\n\
08BExsRG4UxORiFVolhpjZdi3eNI/CSe1/lnnAK30ew9DPpZBiQ+e7CmfJwtYNJBksWpLnCyxtkE\n\
KIq73hKLWXw1SVDeHSVlkk/TGf4yl0snySuI7CFQx6ABmE9soo3HeBGqFUBCCsdnmxeWKG+xGPwQ\n\
hg/vazyoOprDzBrHfVzwWOwuz/NsmCSjwEvNp7DjgZMt5rvZKKlRtL0e69EQrAVRjySNNqxxcZ+W\n\
N8AhoaUCWxoMoSnQj4Ko6ayzJ0nTh4cTG+VK89TZv3hjstg2gv0FZ1GWlVhNSxSLq1GabweBl5Oe\n\
4seFuJSfX8JoacVJtnkNg1hciXg0osMdXgEdJKMUeSvUCfswy4Ep3d+kwxt95OAeBp464pouuflL\n\
IGkitGGW43eK1uAcsY7QdnXMnfdlzowdjopJOkxmw6RFa4gji0F+nS9KmACsStZ4vvEj9v6nZz+q\n\
KfiJdeDzjfaSY0DS8z5Xsk0zIL4VwArgb1WTHiPUp0u6X8In1FzgOYqVmsUaVWhqcYmCpf52Pi3z\n\
JLFLra7S6cuyWt2C1YrVvyipj5KrxXUYEJ3MkY1/+IgbDP6WhHW+8eHj+UbQhv0yjcsqHXIha8ej\n\
CrOX4sQpZaY9vR3hz6Eug5tHKTZteayYioM8iARu+nTkjBB+h3kAghkiNYWyIYfVWDPHHXPFIFhm\n\
6Jea09+ydKZq0aQgx6M+Q6nOV4f8rDqho2QCvPQ/F8kCD/szh9M5hxduN+gHMhtoLsRaq+cWHYdO\n\
X7EUcNDq2aXKpAVWhT/WmdAsud9Diq/UyGvo1sin/p///Gexl6EiVIIec4t/k2w5A64Le79IYadW\n\
RWUevTlzSjgYqzXXaVp2rd5noqZsjyqFjqshwEq1uaXA9wXUnie4mVXFLV1J5CtvLZk6vxvLPzGV\n\
z4lUVd+rBeVmHGbzB7kdm0rXCEwdOFm5Lj+xRj4FWQ2IoPBxleoeqU8Y99IhEFMPkolorAyJWol2\n\
1ow6/aSGptkdN1RjSlXd12Vo1d2+VMMlww3wtMOdVwcd0T8Se52DTr8DGoyPaeBxZp+5rzqvu4eD\n\
N0dH/wCqC54I/v3tzq879LBHZNc53LOK4G+VAs4JrgSSzgjEz0k2vFM6xC0K/UAXfWBsZlVR+NOF\n\
2rSPpMAxXBRlNt2qiBk1AWqXimElZNRkfadYzOckd4qHpHQFO5B67CZJ+GXjZdDAlZLZXZpns7OA\n\
7K2wcQZAd8EF8dGCrUzP9LBRMGrkqOvVibzZ6uDKZupHnHCq3cIKl7QZec5Iq323O77Cdq/0QmzR\n\
h5r8rfX27Pc6J2+qHm1WVAN9CVokSFCkNKelq+nQwZvNSWmho/bef9Sq45bUxzA4P5+59HIDElqS\n\
I9HCyln7BZaFRghkbeQBKmR9AYWwQvhXEr71RG8r+chutNb5BjlhApoMm1hGJG7T72GN39C2gmK2\n\
GQC4f+WJzeDSFtWNPC6ZLaZ0pRFS7e4yPWH+g2+glwcHB93u4SFyH27SMj+QXozl7E1uJiFqibD2\n\
TdRa9kVVOKgWNetQP0TUjKTuAYXC1GM7XqubZzaFdX1efXUFi3RrL/QTsSNbxFbwyzK+FqB7JVKp\n\
BV0jT+aTWIogpHvZop+3t1iP9axOMmf03RaUuyAJ733J9gKmn36+qOtsT6AqcQW7+7ao9I9FCd09\n\
vlZKqBPSAk3Cr8OAdb+rffb3V3y7di/VfGpdWlyBXjXLqAHo7YgkvRF0e/aA8t4169jJXTKDRRgO\n\
0xH8EE94KHS+48HULCRXzyOUJk86Owei3/ml77IkvL8AQWk2TvPpXhoDiwun26COKE0fbU00X3l6\n\
fVMKuerQczhKhc0FgV3Af79mC2AUkwkJqlhuGs8WaL3nD1JUWRImGz4/6HmWu53iDSyCt2iBLBY5\n\
f3BZlwXa7fYlrdRlVQi4VHQBStPwBpTt47goE2X6AmV2kt3jROOUwmHka55Yp8eUUjPyrcnVDUcH\n\
DZnlO+ZeoqZEKclFSvfd4iS5hqMF7ZGWvbJuVGGh4ZiP9PqlU6ikikgf6qY2tw5LVZHnoV257rA8\n\
gZNRc5t0BUpkFl9lizK826ZdAqNe0gldr6cfbpvREq16l4fCH26BUg0USn+Z6ivvtJ5tBtuSA2+5\n\
DVu/WgsorUjyc7zbMqWq19i4wFKhBiX8VVykQzQEoyaOl8lmdb36upDFzEGMwvVW1VbYor+lkOfa\n\
mrF8zb4ol2I3A4YDxJlrO4xaBZDPSFtR1UZ+CYmttzhRWx8+NlW7ZU24qq/VULayS6TM1lBvTXOU\n\
Kgmw3PnwNqjpUbIakJtQcjmrGKvPNi8ccyVOnGWs1AZKY5h8Nhiks7QcDMgmSRyKSgyB+XOdKOM/\n\
v/DpkSvV05rcMImLm12s2ZjLKhNiNexRdu0KtsWm3xIQ59dJqVp5UZMvfB2tdM4je6h1eYDjdH6L\n\
CqJpZp1FeuyyNK+F1fBFUy9RIjZmK6upyGsFs66/+J5Cd59XH3ZuH84icoWR1tV49BucrzBXpW2C\n\
BxGElMeCj9Qrx/LTYonC5V52W7UbhLE9k0Db7gRtNU+7IS/55dkWXtlYG+WpS9JeqlhSX9Ms2j8v\n\
7NsFydPcG4caX3NuQEyLLbeuJsbjY9txcRtq/mvdSr4BOmm+3T7Os+mcjXPYMvJsac+DVc3goCDp\n\
ABfItuxJB6GMrPni/gbl3DIztnIy7sOTmnWfXS/gbHOuTRNYaGhbSQJYb5FNExY7JykIXAE69QSe\n\
/l9PsiuQQt90Tjq2qf4T5hTWbdnJV9MVzcW97bpSVypBo0U/hBH6IaC+g1voMXfprti+n16j7AlC\n\
CysPuBA4S1SRwIqImzjTy4uXk0HW9kZIbT8J1b+1PShoZrXwZula9Wqd/WZfuxubUqPi8AU6icRR\n\
PahXdLLeUZvCGvmI+4nPaOCsYFpzLcm1TI0mc+iguWMz4rbhUT4hHIa8TP7suBRDE4rS0NZWdXfD\n\
8cXdyR+EIxRVZ67l9C7yUO0uK3OaoZAhqjb4eIKM88GszVKicrR5NMVYfXAWJibfAaSaul5ZW8Dt\n\
YGdmdpXiZGZ3KWkd/jtM7v0vjhTb/LueNJ8Y4ptIm1lUv4lq3pNX22fBsbz2hr24G8+GySS4cMo1\n\
igEwqWpmtvW3TVfV+zGQe31dj5Cv3KNmD6ePPgfUyBr39JMg3BndYYugp5xvsGn6fANEEiC7B1DX\n\
hzdZhpXOHrjOK9bVcUmMfq+MgQ2DqxyBtZHVvYCwGFL92c7BweDnzkmve3TI3OOixaZiuyAaTmDj\n\
oNVEG1tJscenQI/Wlql82hK1BqKGea982SjSLSHx6bZsafC297qF/S2z2XZ9jBYBrUczVg0rGGGV\n\
yWvzlqkMe/AlOPAyeq3PqS1DWcPBLu+aLmPD6P3l2gx+J5sBqNzSdqDqsWYb63lHBDzKiK7vYyVH\n\
0wb5O/OLQJyfa9HmfAOtD3Zn0O69wRYsI1lZ5qpCSeqoeODbt+gLLHX8ot3YBg2rqXJgrupiIxtT\n\
jaoiNxaAjIhkbMM4API2BsaXl1k2KbQ/8g2IWXBIgCg1mGSz66QoK57Tq5yiH1x/5raq2YpEqL8c\n\
KE/qtf2UHTdl4fgpi5pbkRx56BWr9QSJfDEr5FX5zDAvXiu8M7+ewBmYpUwXowcY8pBskyhUAsWy\n\
J3/RtnWHbklvoUbY6XR1VJDQB1/H03RIL5FVwsKNkjvjwIimzxQLwLG+mMS5E+VQ9ZTxyLl23Edd\n\
5jUOD1qZq3oDyw1I9FA7Em3y0IIcS8qSfbSAp0bKN64lzi7Q7XAyuYsni2RbS6Kt9Su2B8QscEkD\n\
1cKR95Q1Z+MBLiDOv/ywsO+NHA9PVAmiVsVxvGkOx0pZwa/OAqaP4GKpA4j6qK5I28axp0/Fnuku\n\
mh8FPKpr8NTnsW0Aq9Y6VJqVx0an+7K8K9AyGQgd86es1eN0AByCm5H+GlYXGnpIirophWZfvTu1\n\
657v07q7Cpb2+1/UxkQ6NrkHbrlDgxqE1xnlidjjbW24glbWqaLCeN5Q+JK4ie8S4+FpO7HZfwbs\n\
SrGYkeWWOrC2Aa02rFlmdShwp/yJ2BmNBDmianb1eVvBYxs+YR8se496zP6233yDob/qhlA4KjuO\n\
YECPA2QPdZdheLPl8abRLgW/vHp7sHP4+nin/wa9GEA++AH7AH+zEU+c2QPSXWRnGp4KaEL6Irgn\n\
MepWeTpKngE15MmUbud6QAq9YTJL7PP5CwQ88UF7FRfJkWxVVWU/w+VEGfuAbr1Zyt+F5bmCITru\n\
NTB1QTbDzgYkRsM42a5jMz8uAMtRqQhWRQ14L81xnVEXAkVKrnSvhCFc47MCZ6KfvYWZqnsJJ3S9\n\
WKEwuuWwh2Q1Zs/uFKTmlmBezOIgGtJCvBxhj1y1OPvySc2bWBWtXxOQf8E2a5o4aBhP+KIlp6Ml\n\
aqMX1aGL2rjXr79umtcr6tVp9Yi93miVSfAWOt9I4LztgAYowq9A3I5+8IQN4p8z30MWb89LmNHw\n\
K3QsG9ECYYuR+BC0mr7h0baHPH6YtPBF1FrWwEevp+GF9xuc4aPxGJjjdu22wbORybi1n+WnFMZR\n\
/BFbN83U968eoInukX5DxW3hHUMZQJFsDmh0JPVFPpmkVy8+MVhxpYDfWGAfHp7mk6Xv/5nO7YaG\n\
k7goBF46Zle/JcOyfnONbKFkoXEyVtu7tnMrwoAsRQI5/+wJEmjDrDTHBSADqUrUiigOE6yLO1SJ\n\
0HLrUwG/lgimY30rHxopsnqg6Up+Eg3fUIxxcHEWqKJszL5YNTavdYEM94PKOe5eEK/X9cZYkzXI\n\
4fTkoEYRa1CCisnkJbdcoMLgpizneP7c39+3g2gt0vjs5c/J301uxzb8S84gonH6hO9ODippk6T8\n\
p23xYrN+CUvWkPuYYr3CoK/8weEEjwUw8XREweqs6qp4dY9C4VlMEa1j2KkutdcpQXK4EAdDoTZR\n\
tMQ/weuj0EyO+l7vMZQnGZXNbpj6OPjmM/lRcE21wMJNAw4sw2Lr7MfPIjj7ZzwhcO7NRUV9idvS\n\
XS90OowrE9+3+QmqFBJEgl6yzD5Fp6nc4FsEa5C97tAyy+bjqN1chQPDQF1ZUj7RvaZw1fAnErQn\n\
ss6QsfhUwvNdZes1XyPkeGtJUFVznFXPb0j6n4h6pjlv+Y3E2u5FdNpPCooVPcPNDnxDng/wk9yr\n\
0YV1z5vkXV4wp2bkf7htk9xsR6q3unO5UJu2eDNr9AXycMN6rROOtaLa3I1c3cKNjrc+5x50XlFt\n\
1aIh1Yuz6r32hU94qJZpYk96QK1mTrLKF8kh753JxNIp1zZu2vXKSPNqMNfnASVwtMxaSAnWnPAU\n\
qAvxR+wbz0147jX18GC1WS1sDN7nrlgkGInGIMN1b2Sn2+iNVCRmGsm2NVMXrzA38nJDxgZUjCg4\n\
k/CGAjtsk5I72ZWBDFAETRWgwEXl2hWvXFkxE0BKdOvKd5XdGWpeo0U8sa9i1ac+hmXdvlo1LqGK\n\
VTNuet1MM2jxC9WXc3L+Aeagb6y3JWu0kTF89FO5vfNMgtMF85xHGkZ10btWxhaDVGWHO2/xKi5Q\n\
2nL1o6AqOCunRynC8PRURBd8JUETSHrgnzzyMEsAcGBl91RfG7vTEsl7tvn4JQaOfTvtmi9qora3\n\
Xp9L/GQxnR3ED3j9GI9+237uKYOM4FX2PpzEV8lkO2AivZN3ldlsuC0Vem5I8cQWCYIRlhg3lSDS\n\
iOpNFgl8EJdZHtYGZmooHH75abRtr1M9UsU0ZS4BPDNiNymvbpsFKaqAb8zVhEo6a4nhttUfz6zc\n\
ZPfveElruA/OacSECWJj/UAYXulh88j8FKZHOLwCYtTX0lilr2UNyDIZ+5psPY7JM1SCRStFy1mo\n\
yBfKWu925TZ9a5nDzOcyMcfchgf+szsglyx/VsA/L8o8Lm6egb4Byp+0vaED0/yBo01ebD7/i/g5\n\
za/TidhbzKGwmt8ngjTgIhuX9zF72xF+AbrIMl4BXsqcb7zq7Z1viAN+hUroKMGL/CvCT5BlDrq7\n\
ncNeB8oRxA1XT6ALAghrMRmhx20KnHOBrpqk99Ids4KAEejFi9ANBUEmwHxkIr6L0wnF0MQlV4iG\n\
ia1nz9AucRPnI1R+Ru1ZUj6T/S6eXRWjgfylcmUv7+QdIyD+//jXl+gr8VC0pf/AgC4qN0EM3BYv\n\
pbUfCm3Z0YCD8mGesIuFenyVzuL8Qb24epAc2RjdZOxqMaB3A3nF4voZCfn0ij0cYM4WMBIFH8Hb\n\
syCfGAYRiq9jWIL7JIA50/Gx0sUZtFGRlm3HA0XVbseqXmEJ5+rMHuFiluI0+0dpDd9bdc1W3EC8\n\
oFiXg6x4/3/kWyffBju6XBcoDc3GE9ffZIjrY9xZRngaXj3kCfDtXpkvhlgVHAiDIXRD/TuYVz5v\n\
44WrqgO1XmjrKofVdw3bzHj0dZqhD1VsH13rYyVAQ1/a6GlwwHWFdsVhYMoGfHAjwfSS/A7mpFj9\n\
uV06MB5Or5PybTw86vXKuFwU6CiVzEp51wS6r26zvaTginraOWivvCns6dzv4Q0XhuCdJON3QDYM\n\
xYdDsfvabirHdeBF2BEJl/2sjxum9zAb1qvwFlNzcOs0scd3zaY3m54y2WEGxxQG+R0k8bj3MJ0g\n\
igaUfb/53KoWzUVHc4wkhroaK3ZK6ZPPqq1apnebznt0ZB4jslOBrLmT51le8EcvvM1jn3EedoZ5\n\
VhQ/owCayA++a2rlGDbGhJgNlfurK+bv92AuQr1tzEk/GKcJqHRo/j8Lg5t0NErQ5YeXX3wj/rrJ\n\
thZHnR9k8wGQCmKm6Z8c0AT91L0cKZBSl9CfVRsI8MgZ0F9//PSv7gUqR7Ue9WgiQ6g1cjzENEeu\n\
BO7LQLG0IIkGNEUZpWntdi/0C98zzbzdGc9x79Hk6mfZnIxX69Ch+USOm2rz7yKFCgK1Sz4Yjueg\n\
O1CQiQ7ZbFyeeu+WkLy/X96tGVa6wj1cs0MNvhTX8TTZv3rfeU8wGbkLd3wZT+AZv2MkLe3ATJHF\n\
Ma/bPUoWCZUin/JCDA301XGeXcGhJqFDs4ICmMeLCWHsXPPxN41v6RpfBR3TNQpUg1ueD0SMC38/\n\
jxmCD4QFUCdy4zNoC//UZXKG0WheLu4EnztqKtpqJtqVmbC/WVm4rZwr1v+iMrVtFRhhlCnLT/F/\n\
zq2laPRrkd3rSd8sCm+A/hcy6AE3EP40SeICkYOnc5BTCA+bo55SctcsMdicimEpJlda1j56FYO+\n\
lrTs1zpARA2MqqF4voQhrGNguuRIRvIw9ch0CCtGP605EEbCaI4Mu0hUmIzHiMJ4l8DX6fUM2mYK\n\
lgPFm6fKoi1x5qmU9Hn1IOhK5HoI8QdLfYS4iK8+3oHIaqhv6zkAyfCySncrb1WrKzyHqiT+iU5D\n\
jgICbIYsK1V12escExQso301IjC2y+uk3CnLPPzq+rXbtd1FnsNReIiXYd+CON9OzNA3ossf/H40\n\
Z+gXI+tGi2t1C1vONSBlQv3bmy0RL8psF6MmWGmP/B40NbeZejH/iNNxOMTaw8v9V79I2viKR9NL\n\
JKro/iS+Fk+JqX7lEsllFDUMVS25Z1DPG8awWRuD/eDCY25s9Amz+M8f5IVFhLXaV+lTUg282Hy6\n\
+f3TF9+Jze+3vnux9d3z9l//+rfvXriQ/cVNMhkP6KIEv3MW14OQj77fcPpxE5UjrPhB/9SeouN5\n\
5MWhT6egeHIF3vfxDLgOCShcaHpzzckRalj0F56UCext+zhPrqVY8774CIUYn8fDBJlezeeqjXY3\n\
0162IOgT2J2426v8UJpvQqmmv0pLZUvjnWrfAqu4XjpLHhLUglEmyTRQOshC5WIOOywbi5ALXKVG\n\
FPTcGmMhupYrQwej42zruwvfbUqtm76L3xCrw5pBRPz+O7qEsetW8ffvv/8uiBi+++UL6/Kmjmqj\n\
billrcuCxXFOMZwfAy7goNkp0NFyKH9zZ/M1nLIzhLdWxzgaZlF7MoDjjKZI7JyQAwRbb2T6CrTk\n\
5omKAzHIjARLoExhykXcswgqUEP2rj0YTLPRYoLUiliLyN2tdxxBU/MsUIMGrWrxLkebfNN45VvC\n\
8JlpMXdOZEmfc2gsHOg5gq4XBErEL7RsfEW/Fxqs30AUIfWR7CIyDFcslmPCYptvseZtszXCqbRO\n\
s5U68jnM3NMYRuE3CLrtwzL3zGutsI9+GrpkHrfE1N8ttQCzdEjHWUULtfdtjKEQBYqPs5K1Fklc\n\
dCcgAXzJNJWnBUaVeahFuRmCaDgdguQTOk/mugOisaMqGsHTz4WkeXLQkXbGa9omrA3xE6BT4PBA\n\
pUiSxRz4IGyMU2nAHVlxFNCSCcbi/WKH6iwjkSoo5boYdBLHaA7dHe2q8BP6NVSwdOhXIitJ3ifD\n\
urM2Pg3tSlqk6YVobucdWpwFahKCi2jFaxfwcTV8pj5ZpHvTAL4Jo+b7FAtxBg++dUzXiWpe+T3L\n\
0wpkllnWZCU9/vWlpSjYlwuDuTZ2DRI00sCsV+xfNXO97xtp4nFNWWR5qNQW1r62/Pg28H87wpQQ\n\
XD+nD0mHSKWxoIkwYNtO6N9JjEaja1Yo+WME3h/S1TVpeKbyQsO1AVsE7S0dpvCLSVpC7dh5FEBg\n\
v8kW1zfiPhFTMuAVZaoCiqxOE1o4QfBa9yHK+/MbEJO+wb01YsOHrz+E+aryA/D+LfHO0NyY4EjU\n\
OUVGthFuqVhHLlZmXYRygUAXE8cPMIyZeBE5M7czZw07pcxUI6kPk3KQyABNoE3c3Ti+AigL2IQc\n\
puqmFgvx6roCnEKTMiTzAPYHWtnPEUiluEUEfbyRwT1TYHATSOCYVsYApgQ3GZzLtB4Bj3Ms9dY2\n\
zyvp9yxNYcNsMUpnd9nkDjqPmMJyNvWJFJcxzF15n+AS4H0+7SmE6CbzNnVyBu+z/FaMcmCkBZ2r\n\
94kB/kMLltYBrC655LzE2WLsDXapbZB25TPa6u3Ozu5up9eCVsxaQyMzymHVGJrRoAh5THyuJ3g9\n\
jxni9xQubiAeGkQoRD/EiJD5pxxSXgE+IAPh5aUrpbeMGE68DFHugbvoh218wo5QL8gQ8BZa2n7e\n\
AjqdbwcHCBmbqDwZvHFMo4LCNvjMkMqj8RfQ8ZGsOoabvDoIcBQ1mP6Kdt1Z3gltrrynS3mnUjl8\n\
aa8yfR68Pe31Byr4Uhs1vjFV869Wwgc8Yz+cb1hJ3H6MOTvBdZL/pPN6mcxMSL3DeKYaAdI00Z14\n\
HskUBobJYJqmlLOSxCPGP2J7mEEDsaElaQMRqC7ee44laJJjcrUy4UEtxEQ1libpFmgoZj6rcAFI\n\
wuX7aDM8rOvO8lxbAEVfpdeLbFFYIhmLyL8v0rzSjX42yqw5fhvPCG5lbMWoY+cLCePFbhsj4g9Z\n\
6dT0x2RNU1n/1ocD+MyUaOvBCHhzpi1mlR1OwsP7GA6LxAYAkzNli4ququ6LWQ4+yMr30vxj0Lwt\n\
R/E1iv0I/FLfk9ZLbVzfM8/q3qwqzGuUTtrIQdoxzKn8Ynn1yt6MD0Lv9/Qz3wvCDh7e4DOnAyzt\n\
VefIMWDY4Kde8dOoE7LY+UYvSVCxhw3HIhI6YLQsSLF7FELu84wQfvToMIOXDR67wTUHbvqVxwNJ\n\
+PPdVekDbcVS5xJPYOv9HpsJ8gjlVnHtN+IkvQFmjOk7SJvwocHBfODhWFatOSZsG82ac8Kp+n2R\n\
oXzJiE0yPaRlepHtOKj05xuV+DZZCHorfzp7vnXhqcREQq1RxZYF7mcTqwGNsd26JUKed058JiVG\n\
9PGn5fPD7lp+x7ppmUKr1uoyRLn1kDbsUmtnWXPcM/nuoaamy+5GOkYnOIc/6Nf8rIKvYQUBbn+o\n\
xABu1QMPVcUmXWdUmW8myq3VcNAS/Y2vzkBI/1PgBbN1F6EGjuiNZcHMSHtQ8hLPVIlNKO9ySUFT\n\
ggzJAKw8MUoheyzD5P+2wIRn+EilSAujyxoYonbbKMieVUUdY9OFuMStHF3KFFe2zrHMSvHpIIg2\n\
Va0CRNQhEepcDO0Wq8T+WVEXFoTd8c7uP3Zed8Q/Or8KL8Coa9hglCTv+JZjRGwv260I5EeSZkvB\n\
RipUpkvrs0vbQm3cPTQpGjbusjoUcf7J2Y+Y3VEq3yYztFvaSrJEOZaKBej+77etyFKLoWK9cFQl\n\
t+FmRFgdRbGYsrrDEquKEJfE7bd8WR3AONerdVJIqMZlTGadgC3mRunOnEbsRXXpXOaoakBsri9j\n\
R6HGFyp3hsZAtTMIONunKQVHpwZSh1jLHjhLHpaTA8YXN1TfuM13EVY3DjNRw7JRqI46n1+LwP7p\n\
ArnMnB63gwqAC/uW6W2bjV2vcKWcJKUWSJ/YecRwnXFWFJokQQvRf3rvChF5QGNwN2ntVkGbyvAr\n\
wv9X8JTSgzQhtmezQI40s5NUBxcSyk1nG6+lHX/0IXvrSWVKSDbLU6vKlCgNrke284BrntgRRTxO\n\
WsR174Avwza9j8lsxQ4d+CVsXNJ/JERc2xjoRugMcvWgMnaSHAoz9w36I8hjbbSQtjLKF8Ozy2e7\n\
Sh6kQ9hlEZnoWKuLPTRosXmD4YhIt2RpYYRGOmT2LT4i8XgkbWGKRFlkjF83xSP0ivQxvPmJKUsR\n\
pVwptWcMX+vA2DDFAyrZ0myHggS6a5Pri/LkYSJXwwVNe3jLLZkp2lsYGyH5HE+TGAc7oms0DDtT\n\
tdFM4iqYESek3qtUHkV6NcGP5g9yGrDrUlMs2n+k/5KVLlVVZKWNtYrNUC2apFdaR+YnUzIQ5JZy\n\
DYs7l6zfp47nydL85d7b6PkDLDYIdUa1psWX0dWulu4C+iF3toH9GnSoL6BC/WdY2Elv3yQTeUdJ\n\
6hB2mG5XKnubraIIqvit+AqYHPrPBPxQMbt6wt1Df1tjNsJwg6OmFittNbeCvjZOQ4iz72hth/9Z\n\
yyMm80TDd2cvty5WXoVDOQW+vsXg6043+p23xwc7/Q7bSD58nJOtPjzfwGVE/Nxzz4JVKemHpbdR\n\
5xvRD3JvHR4Ndnf6u2+4Nd0WJq/UZewJcjCQ2J2nRZfwmHgU+b3xVnKjlCwBfAcKVgCssZ4tWFVk\n\
DfGVfBA77q0kGkFDW+J1MsMABJQr44oTG+YPkBKkA/6KLYoDZKVoghiRowV+3esevj7oqJtczEGP\n\
N6J4qZFOU87KCK+uFlZoDdWnBrmFuc9xoCKUgnLUontuum7NH+RlHbomLIqkAT+SI4yRf7TTQjGs\n\
EH+oZMgShxRwkyc6saR2VmRpzC5NjgzbNGU+5wT53HVMsA9iil+1BHJe5CZp/Ino4cFCx6yzYnks\n\
Md15gEP2m6PHYeTrL75pjwdMtQPpwIh3stxVzmynh1AVH2qb7tM6U435I/HlLkYE2IYeekPW5erS\n\
hwVTr+9a5vFDt1LFLcUm8AMAVxNNAV9EqGbko5znCkb54aOdOfrS2ffRpWahTBWre+7PtaH1T8xU\n\
ipMA4wspVB10JBWpzjyZ7qicxCG4qSUjjS44LVHkSzBsNquHGStuq6Vs9NAMxDdC8bZitW+T4qG6\n\
jqIOhYui5Ntk0qd8JSGnLfF7NF3yy0uW/M43bNnvfMN1bxovJhNtddE3xSCakYI9YLGN0BgvfZYQ\n\
bukAAZYIBYt/V4hLPuQGla20lgPSairQuUV+COopwa2MjctS76Kklc6agbB8+YD9NeFFn52f3hm0\n\
dztqFQTGqvAlx2snHofKlU7CCnXY7AcogV7VtZYlOxMiig9ieolXkcKPrf4OYnOKvD/yWytpjNd0\n\
psKJx/mcYZOTO6bycIxqBD2cJHG+M5mosRaVYXIyYHK3s5UM2FRCaVGoTxxyJpVMwjLgKWwu3UC9\n\
gAmyZoUv3lFrSPK2NRHjpnRXvtWoGVQr8HRjT7ZgO0vw2G8m8VGkr6oa9PBY50hnSvOkmHSS+tbK\n\
20vz73UVhcQ2282ed0AdHcuaUMqwUIjLH7nsT+0fpxZi+pOfkBldkuBSandCmr6aBbcm7HGNW0pe\n\
UMTA/vzJ+xrH83GAXykOzqm2r31nf5SQL1grTvNPLfGjVnHVQ05yeJv85D2XPNZiTWIeitI+LxW/\n\
cTzT3cXiwTckX/fQ4kpQ1DXpdwkNu7kOTcd9B9YSaDASHpq88asSh0CRw4gbsM+NqMEeA4JzNusp\n\
1QKH7IlYnQ9cpv96y+6vmHFiaV3Vz6tOjOrPA9KeaA5B8dW11HGw0l920tLJiJf0O2qupUnxc7JX\n\
V+aMB8YXn768PLJ/PWWhUluKckJX6bRuRD6Gs0cmTk0JNiDBahI+CG3uYu0IuXtkMNNyoaPKr5cU\n\
dfblD96c1k55fW+aABNObjBa1XcZ6oERxC/4cdg4RTQ9VkEphUkZqs2JDCPrunk8lomtymRWTdEh\n\
L/QUAHEzmaqkfYw8PUvu+c7LAuLd9J4Mu9nsDl3M0F9eO9+zixXmirmUNV2ya+OlaYSuCmm/N+VR\n\
sGN2lnX87GxF1y8uHEp3vfDMlYxp4zOTYkMXJER0nrQLkIuGN2FwhslEzmcX334VtGSq5M2LqH2d\n\
Z4t5uBl9Tqps9DLQM4ClsYwnBGoExymnjzZzU8spQD2jslv0N+6Os4LzjFNvsGeEziZn+mJlKmoz\n\
xfXF+4w0u2Yd/dS+nGroHsdL0n0VVyzTv3LOY7rzofiIdIzBOSobPRn2JbWTl+MMw3AsN99LaonI\n\
Hb5K0S11LBySPVMz6RAtSMNoIa/EQDI27EwZxh2HXZsIsDFpxkJ1gogQv22RmMNWo7REB55Z+vsi\n\
UW6Z2m+XtQ3Mamm0C9IVpKYCUgMMZMgmk6FzysnRuAPmvhQw7zF0BJSBKWXFZgJ/1+2/OTrtw6+S\n\
yFquPzO7F6YzZ7RmqqgldP5riU2dmAfXgwJ4ZG/Yuwmf0P+t6X9OGbIpvF/EY5hj7WrxwkT+3Gdy\n\
918lWC4ph45o6yGj/8WMZQW/JIaDRFvDulqXI63PldbnTF+IO/13cag6XF81vnoZaHHFwfubemAU\n\
IYbhY5gB/KcOIqcawmAMc50VNmJMkhOcAg3gdlUdFdQzOOcPWS0gRdQbo0ef+bBz3c6dqcpwJdXT\n\
ZT1czNbqo9tKe57Nw1WdZTFXLJ2fwQCLL1sXNsL8HE8q6SzVFmKiwlEbpDrdzSajcZPyYTeGVXJ4\n\
XLRK30Byhh3UrC8k773KhIZy7sg4GiPyWZ4JbJqNVmXFltYqPQQv5J+JFecJ94XB1+Hv1jfsf74x\n\
H/uFdkSo4H+lMb/CdfA6NCXd2jHvy/4EdTzKTzHFa95Us8P70iN67fGfaJNfleXQZ5tfGx/uHiSQ\n\
/8OH+wPw4UJEckWIOAsbTqLFDQcLzP/ZFL3E1qGBautqMR6jdxsIjHlSwMQ3fvga5JK4KImRtcQ+\n\
UQP9ElVB6KBvTmffvDvca4nT7mG/JQ6Od9/1+ict8ero6MDx9iATHK5lNl+GVqeBDjWcWZLPksnL\n\
F7DteFLa6onEf+vdSHQQPDTfIRqUfN+uvVR1IjSEU6V8QE44bxwoKaxQvm1XX9UlGijRPegcHcMU\n\
nO72363CKLPXIjzfuLlH/IkWTajrIw0v7/fxNneDJ7r2do4RVPhWLkC9QD9b9nqMCCYFlmD6qhfY\n\
mT3okRc7V6h7UWdxoWulabrfxvM5qjhLap3Mi38d59k10mY/LSdJYx8v7MnePxq8PfoZPUCey193\n\
j45/hV9fyF/3Ogcd8hB5KR+cdCTs83emjv3B29ODfnev0+vjqvVMdfuDHjw47Kvy+OTwaPfocL97\n\
8nanz+ldn3+vXu0cHBy9Oz3cO4Kn31sfdE5Ojk5Ou1h288V3nnuwQYHkSUY0OvVCTDE5cO3Y0nSs\n\
37ghEvLP3+m6Kqo4c8ov0HXFLYhqhXqrXZkW40GR/ithUDt335h+KVg0o0Y9EfvdX7aIURbAKU0i\n\
jmc3yOftMyMtigVwzJfPzbdd9JhBFiWobeDP/0ryrEUKPYlUN8gxWKt2fGlxTlSXnWHDZ4NZxqPQ\n\
DC30QO5J6FZ+z185fE8+AylYj/7sO8t9KVuU8wXCRHlZbqg6p8svnVWurCVqX6krTHrfpjSi2Auc\n\
u5OEwoADua4BSRzLeNQnAQpqhuyFE9RvFXLB9GpYBLULxHk7LeKrwnMDLeuBEvDeADyYaBh67dsr\n\
TjmUATKEL6xy4EqJNvJYhYFpPSbuiriAind8Onk//4sd/xRLxL6ZYN8x8bL9ffulYAMa0Ckllc3F\n\
PCvQ3VO5mFp+fJIbhuq2/fx8E9RvDu2fkKN5MgXBCIWcGXo7INRlPCSYuJggiGUTpkYCeGFRShqh\n\
zLt3WX4b5ygEm2fiqbpzkls1Az1kcI8NnV2IUHYQx4O3qHRXTZIWEY1Tjfwe391nqg67x3I2wlG2\n\
IIkcB4QyWjpDcHi3siEGtKMsKGUb5TYrG6EwG9k3893hUb+zZfp5k92rdcFZYQyEKeyr/EF6GGDq\n\
CJZ2KG6NRUt7Lu/jB7SBSb5F8W3sepbcyZuZEt3f7hPyLr7OBGodBFPzHj2FUwtN4YnyjzeAfDRP\n\
Zn7gM5qTBSE48EjPtN2HaKNtMfQxXcj6+RPv14nEHIm+fVHdKSRSwOeKALUIGXINUe2DflZR8eUL\n\
Fi5od9mH5X8Jz7mqHqqzk3/n47harU8k8extRxjxvK8JIZVRaNDQKm9VaKFUTWQzPQ9erOfQ4VLu\n\
oSPxRBnEZRmsqB1G67j2w5M7cgbBMzQuHoDIs1u2klOQMLmQEM6R9ImCmgRrbkMgyFt62TZR9wQ2\n\
OmMUjZmTgRxDQniTSAd4MpJmuf54R5vlcXPG3JPwQXraaywEqdM5dfAtgrR4o9WdzN4EHml8f0D/\n\
MhF4jcHOGiB0adSzr1QNdFRTjt8BXRkVWjSH3TKZVsDRqtYzzPDwFgYBCilB/3oAcwho2AsXNVxc\n\
Jft5inHf2dVvhz7vhwDLUAo3WUI5etXMAarD4WQ76AIfhmm+ShjZBev4U7DaomBXsRfPrluiC8tX\n\
3OA/hEhCnYEZqWBN+b5/BZJVV2LH3CbJHEkB2NiEkmZoZ2Zr+kD0IDdj9BN7CKI1Kh9KI8EQ40y4\n\
czhlXWoH4U3jGWGpZkvaPN94ixvnQbzN8vlNOgsE+4MUfzrfqPfBIG8F7XZQw9yqmoNW0CY7gMgw\n\
+dAQw/8udNuVSZudYSzBZXXK+cBZ+fZgBSirBbnqVLgCd9We9y+AuboeMOcfhMsZnG9MB/aAbhnG\n\
9HyjAajUnSkPXOnLaHXW4s3VSKDLLI3XafZ/lsYGS+N1im6rWYHH5oPaj68Z2xyTDFqYZwYaTZXz\n\
AZCtpS9Wb2DGqHLDKiHtQb/vB3BKD+oKHRVtc4VDynBG07DtAL/L6xk5hvZrvl1BVad6wCWcbnOb\n\
2+4eUcnObDFtg6Q/6J0eHx+d9Dt79ZTo4l2CWqVAEGysiOXzoFSqTg1DjdUaF+7S1MaYWG04PdgF\n\
93YGmgV6slLkf8JJEkjoYWEyRcu71cG2/9rCCw8XLEsggInk6XB63P6ifv7fDqvvsCc66BWR48gl\n\
d6pCr1CodWaPuwY6QUI+IFLA5mrGBsqtneXXkrwUbF+svR6fIMt9fmH3tvLps/v0Nn3Ws78snlF1\n\
T7E6XckLpxK8bgPh/7adL56NsqH8Aj9o35TTCX9FEagwe6YnL3UlaBUawbwVtf6QOp3m1Lrzy9MJ\n\
KtSlaYCr3ac4VlivGRzDdzIhCGsC7vyS8M/0TR4+6raW/appv8rJTWcjg6al0S2CohEJ8ZF3NFUI\n\
ySUZrJpuPKhFFSgumpGrYJ7LalQqfcspiaHWvNDfU1inFaLapcfECiwbkoIz9FRXq2jlxUxL2Fmq\n\
PuVccUZWcDISjk3Qv1m9fmmKchoVVZR/swa/o2IR3fFTeJGsOFxEWxbbrk6MZXFdqCwpiLEFJwUF\n\
ZDwUJZInPEfxx0j43ITM8nLlDX+9Uklg1qnvCXE0NQHK8VdyN4S9BiUKw9nzlriBXTmRuT3y7BrJ\n\
HxhsPE+KlqlNZicDupH8lEAbEbiK3PowZlHvDLoLGex1TzBnWkDdJD2ie4jGUfkYoQnM097p/n73\n\
F3rRlpCg8jVvT5mPBfnl/3vWRjvb5Flxg4MB/oJFftl7Pdjb6e8M3hzRLQ0wFk5Ggrs4VPSG0xZe\n\
BU5hEMWvArdSqf3h2/7JTu/N4BXXSHf0zsf4LRFq4H6B7glqNa1qtGqxSEdMhNAh+JntA/2jY5id\n\
gaoApoKrtt7t7xwcvNrZ/Yf1+ilFPWgrOtQW6fQ8cTFM08DJB5QWg7kN3iztRFsVezmMFrVYCzD5\n\
iejOaKHZyTEG1uUk7XFjWdcx/estVTHYE+J2tQv4MGpqiwfS2Jqs0GrPqc2KRrPvxqxSOsaQXf0J\n\
gIMybm5V6qA8xUWZjwlp6nzj61+ffj19+vWo//Wbra/fbn3dA63eda0dZyjnhkU+bCEsCpwzdgx+\n\
u92GrYpQlVKvJQkGJv98o90GaUcfS4x1TxFShPSApc83SIyCYuj6aSq1P5L6Ow2e8KoV5gWh57ZR\n\
BrAmnTuosppLeEaLpPg96LZ5JbAaHrh3NFiiMU5Cl86TiSqtZ8f1Zx9nAoqeb5zRXhAIDnWB+Zg3\n\
nCLfYhG8NtsmmAI6qqgLhFbQUJ7i6zAXFKwpf1ddfgJsYbSWekUalp/BYNyMYSxmhJXVRriQzb9s\n\
bupA0EKxN/cqTIYhOV9X449oHTYzqM0hOGKuA7z240kdFaWaWdagtmzbtrz8hSZRKKNLM3vhiNQM\n\
wyD2SBXqEyCyp9VXUp0JkQ2IMVChapINUKAG/BY6ULraroP5EuieYtOcpkWpo6xM0BDZZm4ogFdP\n\
ouqNHktLfw2rimDOtaJqLKYkrL51jEXuqqj+fbvtppCxOqkHDRVdBcLl6PL7GleHQlDGmQmbtvSA\n\
Iu9rNQhnKoGAcr3MLbF0bjQR0Bqhn++608MOwPp76fLrZYVWqeEkK6yc3SrkG2gZpmcwz1I60uyj\n\
7InoYMA3xQ1J1M2gYMhNNLw+gz1NWhnVIKgGgv6hu7Msm7P2AItvIg+eEBqeOpZQ/llyIi45Sk8k\n\
SC5dMt5lKaqyY/RP5pZdYtUX4NTRpVfgHNJEJc42LzwHXG36kMxYg5IelAM2rchneZaV9oyStI6K\n\
Yd9Ri1I4OMLnEZMYXxWJti5ioLHIJmBqs3HZi8RMM3MpzuKkyMrqUEvYolLUyCB1NX44GXlDp63l\n\
WjOYoAZlfQ0nOsJ7JKbj0JlncnzqvIztc3VImXr4saQKPqGpNKNR3Vj1FWU6vH1gudyaB9v7AQOZ\n\
TZckZ0oLrLryHD8JaTR/Jl2w3Rt0ez/3f1lrFnxTr5+1VgiaUZNtz2E9prcVc500QS3rpvVIV7OM\n\
phVg/OdRtbLoSYn7KxTfodCj6VWJ77aaxlj/U5VkzyIiNipO8LbfbJTWEsPeF5n9BispGS7QTGoj\n\
4289wuiYtMe+uEz64lNWdsmC2suxNpOzxVz9vZR03fD6JbUvIbdVY3wijslZhYLEQNumKF44VugG\n\
nvArFlci1OcF/nqFWjsxK5m7IrJdA0fJXeWsMGgWzOEYX7egouu6eD1GxxtcNWp5VewjmXsWYT4b\n\
6plbOQ/p65u4QOwo5Tc2GIxJRhkMgipw0rF2nBKoBBBK1TzPymyYTTy8pjL8tqnZMrDUoWqY9GEi\n\
pJEd1EA5ImTKuuHkPQZQYAop5NNf54H4Wmj/twrsY/VA48mItpqt94ztYCIRtsTXBcg5Xwtn9kmx\n\
lIYcPrLvbxK6aNCpRNBtkoP9hngdAFzKPqx19hVTY4rOh5QOVBTKaY3iAlWGl0y5vUhirSqXEmgh\n\
HmKDcqgtfPJucPSP5WOuZedoGjajh+usFVeye3iVUNj3M/I6BnmhsencW6NVyRJ0HhW8Bmrbkh9u\n\
Kul4qHYiLJ2LL9odC9dwBYRi2htlNCcPiUT+wNNApQGhTe+IEJS+pWIPYIsda5Iq7lLlixgvclpx\n\
toZXsGYld3JG4JrUroL/F9So1Yx721ThMk+2IGy7466qRcw+oZRlO2sGHlZVetUBOecV5u0MzDIs\n\
2JGWuuSftvXAGg48Q4m7uKfw/o4uFCzNgoRiH1HWxuw/6CqdtPR4tVNMJY6tpMH7a2VarEoB6Qti\n\
oIM03LaiNEGOTCbrL/rbTOjWE+20RTKPMbZVn2sSxg6Ot5SdLSWmrmlBsok/LuuHhVJqPcVsKWvk\n\
ATF3F3wj2jbHhs6zoZ88OnnDkzWyN5z2dwevTrsHe4O9zv7O6QFGGwQvNjc3n9J/YnNzi/5rb9Kf\n\
Go4WXs8Q3DhigDdAaKFHFG6G+0yykTg3SRvXSsBXA/aPI0IJW13wqo6JpVCPqdvNqF+kECsQXIUY\n\
TUwfd6Fxi/L338UpiedzFNM4mvCZ+lZhxFNundrMuijyjd00GM7xzA4obgs8GZzOs1MAHQMtqScM\n\
yQM8mc7LB2cg6hsSBLYrU2Yx6wqokf1Z1ATqrQYlOvjRFlmqnA+bohKfiD//+c+ERUYmjyEZtXRi\n\
x8UcTyRVkR/e3W5meYJDlcOgZyD+cZUI2x/THLYkjPxgHqd5MUCf0m2LFbStlWgcj6SWalMNGHYN\n\
tYc1+iZT2H9AZ/VwV0LEwHQyNLpJUiW9qr4jzoyPKSEG8sKMOC3OJ134ZSZM5p6B3xLOEMVkRVvG\n\
C2vIplma1dFiOi8sOHLVeFRHAnBJcR0cAGyoNknLEyZ4J8zZdewlzGoDIWKnWvSV96ScegrPNg0O\n\
mOtZ0fuMsUBShRXEYr0EcCS8trt4ko5W47XZ6V1EhzsTMFJKwNk9ZovpFTwkvErg8M//FnjGmDqI\n\
+Gxtsn4HKUZV6jUeLud7CrPQnmh6IYHLg0bxbL36q9XUYDE/CxNTn3S86POoKZjZVjKX4U8Sel8f\n\
7/jqYBMW8kUTTCQOuZK2PGjmaXQlVeFhTaj+VB/ecgdu4nOoviYu1DZWLYNKNXGPd2/tWfkpCfOr\n\
0LTHcpzOkJCg44aPn8jmZO6QFftb06PppH3L9MmV6EXxQdxWDkurw1WQDG078GUeNl8JvAY4mlH8\n\
cHaPiS+N+ChT6BUU6VNMUEEt2qs7pUb/iB7pT8SyTFD+pDhVK+MomeiPzqy5vjgzc3zhygRHFJbB\n\
Lo7I8CU/jTFiaXadGPDtG4o8ceG3PWflemmE40Kf0+u4N1YUoYpz40vxRrkCip5yZQybPAWj/wbn\n\
R/HFvR/FZ7g/un5un+rwhXd4mKlQZrBF/SEYxTlsnsB1cWuzO2Xx3q+DkeGwVhNU8/KFtyJ401SR\n\
dcxVdwIZdmS8Ht7pX6cZBsqVnNwP9FoXWUW3BuX8rVk07fPPk5sJcyYj5AO3pEzRJPAtcpHdu9mA\n\
taZq+Us29Is3qLdnrnXhepHKXfJF40XoISaW1Yki0b4YT5qVdjdVp539Q7lpku/ii1quTsqAa3qb\n\
cUh1WWIPh2iPmR3ED/TUSQbXkubQ025LJCD27aEHb45GXiuZLuzMc31cZ/eqItjPoB7sI6iDFezV\n\
ItCI8SvZNv2iv7jJ7jkOEDEmr9RjzjCJf8vKTHP6Idf3Op9zwR61fUBaJZ9ElX3rMEd/4lIyIO9n\n\
OaVY4iwOqzObVl9iqOhpPln6Xub/dQEzXi/SGuyXRGoIdOdV8qUkD1ZCg9WER54XetfGmtExxYOQ\n\
JI9AIgJTuFGBrNYauS4jhtLCePRbPcyr0kd8X5dpFY2Fs+H2S6DY8uX2WTBJxiUKm3jsktCJJ1lw\n\
UQsiI4cbOAGSyXZwenIQeILRoOuwj4iuZCQ//Rzeb7/c3KyV521E4YG8GhQWp2qRz1aEvDXOAfd2\n\
Owj+B2fpn9XUdnqW/oX5FyuzpHcidRu4DPzTpqi+KzkryDpeQfcKONNpSqFz99C55y3x4t/gl3/b\n\
vHjMJEMn/vBJNs3vak8QyRdMRyoMA93BOQGsWNny23Q0ApHkbYbn6CiP+YqJmKNIhyhMZDM47x7U\n\
gUdvKO9Y8iCDARIFxM/4uRhLnCeorrFMhEdY8/gelTWy9jF2psORPGSXW54RBaP/Qfw4U1p7ixRw\n\
OpPCO+YI0cWWDwyb1WKpCD0i1eSdB7Dcmv27JK9RjsHfwzyKjFQmLaOohd6hg/mHj1Ej3Ju6+8M7\n\
Nxm5GRq+jTvPOYECfw0u6Z3qmwlU8Lh3w20pMzDH1ZpuS77Hsa0G2LN6TGkjcYgioHUd0AgDEXlX\n\
xI6oJkdztlngcLGixkHVVrOWfgE/P7PrvPCDrZvkAFJeCKOmIpasESqgugE9hPW42X7u4e3LJksj\n\
ncIEqQGfOZN2sXTO1LylU9BVMKJ2Ej8cIMfVsb5Yy9IppCqg0JmnEsS9wHdsNSG/LZKFkfaCaGXH\n\
sD6nBnpiPl4yIuo9ll7Z9yeoW1sDCC4eMVoaoUw8th9P08lDez67DpbV4I3Or3WKMxfC0mK8um2r\n\
IC/Ka0QAzkG5Ha3sKzDuCnlrA4VN/cpkw3PuT7Wysq2a1cQ0H60csm9m1efLvl1F2pNPJedJnYRF\n\
lYbFSiJ+wpUV5cNEUgsOCo0zwapuLB0Zbvht8QGPrdtoi46vO4a1vAWOq4aqzoaPSFK7cNbFs1Eh\n\
Y2kpw6YMqROhwUB60f7L0qVuQnetsTmWwkLMlYq9XVopa+Ar65WoG/4EESJaq1ssJbTj0Sisecw9\n\
ZhmWCHafIP8ZvTNcJmZbI/BlnXJTqPfZbDzJ7ilTKVuk2ILMcFhkfZTORGmuZD0kmS2MtzifBQxq\n\
NZMYqlbrUbQc9lhZuxkIVwsCXhBi9/IPBbjaUHbyhMRJQoLHH5STkHGV+PDx7y6oL0j7oG38SuJx\n\
cIiIT1OY4IqiUZlfah42KX5Vx1CxxSUj54RGzPEhSDvzopUxOTEwGe5ckKhnK3yOKtgSv5N02hLl\n\
+7ri6ur7bcwrrzO5641mWVAsabA9jWF9o8CLZWO0m3V7bRQwR0dbu/ug7n257htdz2OE4JCubduW\n\
FI7H28E3lE29JcbT7eci8uCD1Pff6tEnZvRUxZmlZTrgQa4W1zTrlWKs/O3AKjm3T4NhDC8Q0vTD\n\
x+qtlOIJdQAW+ZXHZVK+qfjt1s8EoFk87hQ4Xx7ftxmgD33cKNHXrCSsPpAYhhnam7UHSHGSzDP4\n\
DXHTnxn4DOMQ4l4vFvMMLfjbyvKI24UuCeFfl3r8pwzf71VPct+YJJ2rJmVu+2opM+P6XrFgbUJ4\n\
urMksZI87s432Hv8gLk1hcIBYzYVVi4qZfssM6slBlo+c3P1BkEgr1yPuQxG+IUuwGkzNeDQKcBK\n\
vjvDDy+4TX4XMB5pNYaEX25VQJCM1VF2hndsvtoAqT4Q8ougCsv+R5sga0D+eLOx/blWSPpOLh4a\n\
kSV7NVblcJaDvog2bjb9FAQUJCcj8lmO2JRWM16lHssVvZARdLYdLvCPWF6jW+b2EJHiCDyGzE/+\n\
zzDdyrFmQcvEIXs90+VnkW/fWiOxJrA6xeZ4KlJeECvQa60N6+cknnPZ4ry8cUBFINAqZWOoU+jr\n\
RbqKQNFgX3F+XUqx7PZnkU1zoojPnMGawVETmDkVmcRqMrlNVJrYrLMUatuuzeb5Bk/n+UbFZkMu\n\
hDbZ1ZnCk0dbIp9o7zs41jEeNSNIB6ojniDDe1A1uffsHIxMPTmkuaCNhLqYHlBzlo1VS6FmKN62\n\
mlgrf4C89cbLRnMhHw4jQhxq1SGHdtD4i4XQIQVY8J10d8f/nwAjKBj6Q7lO0UXtTKK00ZOrdBYz\n\
quu0aEkvHw5txJmcZiMNptOia3SKlyjJJYwBNUecgql0NB4QMoAJaWyOaVI6xrBvhNs3AqmVnSKl\n\
mAIKYUvH0h2AkzIN9YzAaZYOVfIplTrKblQ6b5seQXNwyKXTxMS31XsBrVnzoXoBAx0thskX74jy\n\
dRhlw4UB94EvnmEYJN1Og0aV5CAbF2a2ddSp3XVrTIeW4x+xDuiQx5mjOxu2ofemHK1BCnSEAiLV\n\
ixZ9oFcFm0DgvEivBWEkQIemWUkhRzA7Jfpw5OkdhmDgTWfp+IEoclKwTtJpE31dQBa1YnAMvuqb\n\
bk/0jvb773ZOOgJ+Pj45+rm719kTr34V/Tcdgcj2J93Xb/rizdHBXuekJ3YO9+DpYf+k++q0fwQP\n\
zjd2evApSGz4aufwV9H55fik0+uJoxPRfXt80IXqoP6TncN+t9PDsP3dg9O97uHrloAqEIlMHHTf\n\
dvtQrH/Uombrn4mjffG2c7L7Bn7dedU96PZ/pfb2u/1DbGsfGtsRxzsn/e7u6cHOiTg+PTk+6nUE\n\
Dmyv29s92Om+7ey1oXVoUXR+RoD93pudgwPvOLHvzihfdaCTO68OOtwSjHKve9LZ7eNwzE+7MHfQ\n\
v4OW6B13drv4Q+cXypdy8mtL1tnr/OcpFIKXYm/n7c5rGFu4YkpgVXZPTzpvsc8wD73TV71+t3/a\n\
74jXR0d7NNG9zsnPwNR6P4iDox7N1mkPTlKMkqGGoQqYKngNP7867XVp0rqH/c7JyekxYh9HMPJ3\n\
MC3Qxx34dI9m9+iQhgozdHTyK1aKc0CT3xLv3nTg+QlOKM3UDk5BD2Zst28Xg/ZgAvvWGMVh5/VB\n\
93XncLeDb4+wlnfdXieCter2sECXm323A22e0pBxjaBX/KNFsy1aSdHdFzt7P3ex27IwrH2vK+mE\n\
pmz3jZzudt31hI8PDJL4sg4oFjopZ2ZYx+EETr37PJ5bj0C/Rm3afgJaoN+houIvYevCGCb8NlH2\n\
GQeH16B2S9dUjnAynqrAmfaSO0JBcQR5B82jmlTEqDC2q2pDCfOT5TO3TmlKI7ZW0ao5Ya2PXKTr\n\
NT6wJarHfADz+6jyStp+7DdoelrrG3bIWqOgvX3WKE4Rnos1O+GLOXvMZzaS7iM/ffTK6y91ivTH\n\
fVbJLfrIr9PZMGdvvEkvvkt6w2RWH7G/OpKSV25RKtUY5/eIr6Q8/lkf14X5z6rjS/WFUQs/txbj\n\
3/q5NVnwxZ9fT1a8/zL1SMDSz6+JU8CZei5cbCfCZDnTR2obRHO6p7LiXtwD2XpkDm3roQ2YaT3O\n\
isoDdT7XUPspk7ryfZyOajFfVdtO1ZPSNdbgHTSMEE9k19N3y1uODFW+oz748NGOBOIP6nWksy6b\n\
wdQtON2Z1bxKzKWFilkRJmgFr6oMp4k8bVy/snpWTdlZv4K3erZ+ok4TZmN9vjwwsGIh9wfUrLpW\n\
9Q1ROwPVo24c6/LaNrpqnEJTp9RK2/3ZakoHYH1kKOenNSqw7jyB3tu1i08WxqzAgllyn+Qmdm5s\n\
6OnvKo/YTP/Qke1zpwTO25b48OHjR12iL+usldB3qbUxtMwQo8aMhXj1ejq/zuMROezsEpq4x8nT\n\
unfFKDr1SSN91TOGUs0Us8F27bUdqBo9cZatx152P6MuMn40QltgXNYXXpAM40q+/ILozj9mScxH\n\
X3pR1kiD2rwQOyZC2IqHw1wmnCZWoupa0yiTikjwsFHCuavQVFlbJrnr1BLLxf079slZihXzzpsA\n\
q1o64Q79U2k/WT5ulnWwGXl57TOZPjpY1IJloUho1mQRJcWu1g7fL+wA2vpERRfVqlHxkvox31A7\n\
sZdZVvp8M1c+MAGhngA8AnOlDMq1m3xz9lHTyjFuvPz4IydKfW5Tzd41fCIIGj6eiOkCo/BgIjFP\n\
of4Uv3z2o7TX/8RxrP4DLCeZZawicxv888aE7gRlzzYvTGQsB2fi0+cXa3NFndOQQ7JBzFTwvxoZ\n\
p6kHVi9b4nl09rTebPV3RRRn4wvyzhhV7tptKbbNubPwotyiJRRj8ZqcJVUJp8eB5SEKoAShjmnF\n\
QivWXn0ftcTfJPIs1RNVJWfdZmA1aV33UwuIUi3bUN1g4GrZDd2aiKKKL6HTRlVCd/SCIPAnbScg\n\
gXSmZ7LxIgn3wNz1EWVvL2uHswtXjcTkZvNsUFWp10HSIFLZoqr81O8qWsHf9fam+rvZyqo3zbgI\n\
S/ARPDMdiaiaAH7pglmfoqkxT6bqwtW+mqsEHcrtVs1YIa5ThF69tL68bIyEiguuZVTVbyztScaP\n\
6jXNykNeU6sFTvfuIzQksQldQD7AEmWjBZLabfIAlObNQF9Nkyub8686xT2bevly16ux2AO1FT6P\n\
VG8PC68hTf0+jw+nfevTWjfW7oL00jHlqzwNUVMKkhSpLotarPANC/TQ85oDOnw9qGXgq5jEvWW0\n\
CdMTwe6tqeGy3F+W0aksnBM3SkXF6NijQV1QVkHa4DY6QGvccP0DFGMM8drHRpHc9gyz7eJQtGqh\n\
RhxdsX1WJYIP3qReQ/a8DrYw0sKd2h9qPoz+vGDsFA8VNLy3HNOh0PSmHoTwsZaxW2f6cgU9yXdQ\n\
B1HW00JiNz9QWiZer5HBtqML5pGFcjPMF2OUsm9Sk6u2OfWjbYRekl/PsVUPoaF8ZzJRD4q6aNAU\n\
ZvtJhEgb6r+TGKlDDWToWbSdEawCw0sWmP6TAUFIUF/M2TiX3ClFoRAhOYGDUqVwRVZtUZVWtDNC\n\
OU6HzVluePLegixY1aWW735oeqH+9bnwIhypxRBdD1ivamj1aUGIl+MFAl1oDxwrX2ZN2vXX+Ce8\n\
cj866e8c9sWfPmx+hP/84ZJW09qZXthRk4zQhRmR01LE17DlW1BZhquWeBKtyjzHKjaDbLYSZQoq\n\
aGv9CnFnQZctknndMV97keL/MAzEqsP093qRNm2cOmkwq7LA4B1QGsr8Q6017UlYCoR00rITOX7u\n\
wyqdJGQ0tJ0+7dX5d8TmTIeIOJ+NXEe3sUCWMDNQ8E04RDVwPB+YjIZtqTYyGGCKRelMSmCQ0Uqj\n\
ILlm5TQyOtBr4am6UJEPB/OGaESO79VjxPxelo77iD4MWJrBGiK/x3EAvBy53YSAxazOR945catd\n\
MjFOXRSB44yiKQCWIhsRot1XJ9W7uOIbeQIthmIN6orCWWbqI9R/6jJV0ByiZgEiQ0HGQ6YeoyoB\n\
lA8PjS1fBpo5Q9363HiqdFxdfrvNyJanK4S0XuCdhzqggTUitprSejX9cSDJzcakTa/o0SaxseYJ\n\
qMAYBrHysK9XEOp30SqGVv0X1Lc6W31CZyPdoVkhUsj7nPBJOiUt6+IssF9vqLfwU+QxjJkGrAq4\n\
JXE2oR0yQXKr9YAMLnQkhNGFWNmk1RQfNSG8BaVPPccwsI3oh6Bphm6SmM2LSzRf/PPsG/u3HkLk\n\
MICiPJx16ka9NC3xGzpAyhOWEpITpv9DLLGac7bz2hW0m1Qv++cdQoSXrp7qnDWHmDxxeTcghpQy\n\
5UBnKS8pWRfsm0yaR7Q8s6VHiC7s7ZRdFiktBZ74iOlbYGJKdLtECw3aqSknHBmyF5MyxVUTQysn\n\
hrJlYEo4pwA7vaKrZIyG7Orb6wxD5DLq+QT9Zy0UanLTfFYxb0TNeHtiKeDes3bb2H+1B5XMxhzc\n\
B2IFFqWiH0NwjaF0NZRAy/eKQw22PBKkKeT0AA12Esu1Or7G8fKAjbG3UZRcUvlStEIfwZqFULX+\n\
4ZiGtvi/Gt8QjXP/TOfKntVCF/j5oqTEVy3KEn/8MLQXSHOeAlNq6xniZCyyFsQxPd/48JGzCeHJ\n\
Gkt9RQu+cyvepQp4Tz1ws3jRI2PaIrMWBvq5ljzeT7ln4eaV8JrhojwmCPJtEpasb3Fpn9cSqm1b\n\
JfxkpDWtWln9ZkC2xvlDsGQeLdzCyPYpYHdyxryPR7/BkcBxtAztTIMLavnWpYdl+58YyYjyEs8j\n\
be2Weds9RvI42EG/XIcy6yEPlMIqzYuWvFBiBNL7eHKrp3jLJw42XNpUDMtjoPt79OBsJ7ORFIsC\n\
mLAhMiIMkWdybJRWrPxscxsdYdz0QZwPKznRzhRlbF08CkzB8ESTs17WXpO9Lf7JMTH2FVTkyWtf\n\
IQ5NUL47AV21LgX110nQkyq+4hm4xGPYdQtuVT2IbR7DbrzKFmQcjnRLBv0R4ynwQgrJGj0bEMBF\n\
uR2rCvbMh+RjYjoMc3410c7BjK+a5Pi6UnAIGymbyoraqqDOQrr+p6ZofSprzqx6Ng2e4SvMg9I9\n\
Woqr34TJV3W2+nSEOQtBbi0U/hUg/OqsUucLBs3BIBzI3DdAPfKAKXCzlFUBwBI++3A+YR45DkHG\n\
uz9B1SHucyMYgYpdNh9ZwcrjrIBW7V12hHjSGPaMRh5ki16Qb2M1eYsIHIRocJ+whIggkzIVJhpY\n\
F/mkcqbBE83bbKUvDCSCKLIX1e2gcgNjRWTjW2BosgF9N6XCm+MRUBse5yqCWnfaex5ICuRwfSOY\n\
lMl0bmUCk2dgy05YaQsZ2Cw6mnVn2DJ+7DRtA267H8bFbSgqfaiQic+qiPNp44PX72hqljQDaLxd\n\
hSuQv2LXl/TFZctrBxoaGWKJsboBWNq9vKDwtm0k/ZoxWU4Jb6U1jKJSzmf1IimTPwVeBZotRA5F\n\
bdXt16+T0pZBVPxWUtkDgdmK5GUBb5vyKZwkw4RCwfgTkHZGqL4F1fBata20qBAw8ADJhZEX1uBb\n\
2EXP4FS+gfqfWaXrQvZa0AROp/EL1t+2xAfjaaQhB0i9dxbNeYVeRC82Nz0pnSzHIVgKqFsSOcwQ\n\
fQgPkLxgpVD/foGQiPFVRsmmdC+IZbpdqaRd2sfcPKgF45JLxVyJnjpLiHKWUwl8V0Mr1HNBx96D\n\
kqNE/oAgpaZUNQ0YzJ90tv6RZ+dYunF84vF5yd9fclZXaRtRGNcamuGo39mqtoBfsMwP4uSDVGTR\n\
w70g08dipmGSEdJX52bgr4aWxcLqzXKdZ2x80uy4BTyYyLlSqpLuIDBlnLCKsxdhsPQEUO3qBM7c\n\
8uexePeY0/MBW+s/UHPD2yb9sEjRLYRSPlk2HlLnkqJs/xEnh6Qj5/Cwkq5NpyB8Q+WTB067iSYv\n\
jXZusZf7mBHpOZ1tnlxlWbmO/i3Vf8P/CHAcS0jXG/1xpWdOihwEYYdNYenaiIw/n+cZ8ABMM++x\n\
JnzusdiQK8yKhbJSgR1znHWh7goxEQ0iqsba6ZWZKe7GKwIboIR7Rawi7xH6a5oxvYwXEwYjwOIw\n\
xitYjAcmEuimDniflXlGoitePepUfiYWGrcOoq4fHR78io3hBKb2HDI1wuMCce3Vza4zlY0uAGoa\n\
1i8pFbWwdmWAHA+HwJYKrcpXvav6cvBLxu7LbPCYDqoERrAqWj8MVdciC4bnS+Zf4xPG9pWwQ3bU\n\
MzLvAe88SJH975I+uitR7Qt7RlHmsgeikRQZGcj2J7SLwdatVBoGBYbcoetUULMeqrWs4g7ZVdas\n\
UvZ4wkBPOxudJbviEw2VEcueopZqXyXN3fLYSlTxug+bnrjQ70Aom/F6MVZa9hY63/hIxmTsRRhe\n\
0kZ/+rt4Oh1fRuK//ktYj5L3lwhXtxlF4sP5hre2M4cM8fK6x86nMpnUi+jC+x1eIxyNx3BIbD+v\n\
vvcwNH9KQ6IgLf/hrat6qh2lzjdcy/M5fP4j40ij04bjSqM8aFQWl9FPLVMNerPQnWeBVRyRqAsk\n\
pOAwVKZOzCCFaNYIo2OP64yROdHj7InYEeo3deDIKDHKHzJLYol+oYWH5D1Q3DSRjnjP6Fuvv9X5\n\
huU/5u0oZp8rmKEPMe8oO5IwhlOBeBvzSfxgcpQ4HhzO9Q6mQSPgk9t7xPOhs9YC5sSiHytM6Esy\n\
oicqYl8GBNKzlekNnixLYQArM8t+j5eXAyXTKmfKLhfJYfLUy9fwY4ygIzDDbkXWTGHmKzz+M1q+\n\
n2Ng7O8tz6MBy1iE1I63VJYiOQF98VR60G1XK/l9aR217ChuXZvtTYtt044pyXFMPHVK/iS+3xTf\n\
8F8vvtvS2YI4XXGGp3gMKtaDcyni9nN8tx0u6WnLbt3SVpcjFsLUbnz8/wREw8c=\n\
'''\n\
allFiles = json.loads(zlib.decompress( base64.decodestring(allFiles) ))\n\
\n\
for name, text in allFiles.items():\n\
    filepath = os.path.join(scriptFolder, name)\n\
    dirname = os.path.dirname(filepath)\n\
\n\
    if not os.path.exists(dirname):\n\
        os.makedirs(dirname)\n\
\n\
    with open(filepath, 'w') as fid:\n\
        fid.write(text)\n\
\n\
\n\
def remPackage(packageName):\n\
    # Remove reference to the given `packageName`\n\
\n\
    wasRemoved = False\n\
    import sys\n\
    dotName = packageName + '.'\n\
    for name in list(sys.modules.keys()):\n\
        if name.startswith(dotName):\n\
            del sys.modules[name]\n\
            wasRemoved = True\n\
\n\
    if packageName in sys.modules:\n\
        del sys.modules[packageName]\n\
        wasRemoved = True\n\
\n\
    return wasRemoved\n\
\n\
hooksExisted = remPackage('mayaHooks')\n\
remPackage('mayaHooksCore')\n\
\n\
import mayaHooks.installCore\n\
import mayaHooks.packaging\n\
settings = mayaHooks.installCore.loadSettings()\n\
mayaHooks.installCore.update(settings, 'mayaHooks', 'common',\n\
    utc_install_time=str(datetime.datetime.utcnow()),\n\
    utc_build_time=mayaHooks.packaging.getBuildTime(),\n\
    shelf_items=[\n\
        {\n\
            'command': 'import mayaHooks;mayaHooks.main()',\n\
            'image': '',\n\
            'annotation': 'mhg'\n\
        }\n\
    ]\n\
)\n\
\n\
# Remove old overrides so they get updated if needed and don't leave cruft behind\n\
import mayaHooks.override.baseOverride\n\
mayaHooks.override.baseOverride.clearAllOverrides()\n\
\n\
import mayaHooksCore\n\
mayaHooks.installCore.update(settings, 'mayaHooksCore', 'common',\n\
    utc_install_time=str(datetime.datetime.utcnow()),\n\
    utc_build_time=mayaHooksCore.getBuildTime(),\n\
)\n\
\n\
# Add a user setup entry to support dev installs (and icon folders)\n\
mayaHooks.installCore.userSetupEdit('common', 'mayaHooks startup', 'import mayaHooks.startup;import mayaHooks.startup.startup()')\n\
\n\
if hooksExisted:\n\
    cmds.confirmDialog(m='mayaHooks successfully installed!')\n\
else:\n\
    cmds.confirmDialog(m='! IMPORTANT !\n\nMiddle Mouse drag the mayaHooks shelf item to your own to access it again,\nor see the script editor for the python code to open it.')\n\
\n\
print( \"\"\"# Code to open mayaHooks gui\n\
import mayaHooks\n\
mayaHooks.main()\n\
# End mayaHooks code\"\"\")\n\
\n\
import inspect\n\
class FullReload(object):\n\
\n\
    @staticmethod\n\
    def cleanpath(path):\n\
        return os.path.normcase( os.path.normpath(path) )\n\
\n\
    def __call__(self, top):\n\
\n\
        self.reloaded = set()\n\
        self.src_path = os.path.dirname( self.cleanpath(top.__file__) )\n\
\n\
        self.reload_module(top)\n\
        print('done', len(self.reloaded))\n\
\n\
    def reload_module(self, top):\n\
        self.reloaded.add(top.__file__)\n\
        for name in dir(top):\n\
            sub = getattr(top, name)\n\
            if inspect.ismodule( sub ):\n\
                if hasattr(sub, '__file__') and sub.__file__ not in self.reloaded:\n\
                    try:\n\
                        if self.cleanpath(sub.__file__).startswith( self.src_path ):\n\
                            self.reload_module(sub)\n\
                    except AttributeError:\n\
                        raise\n\
        reload(top)\n\
\n\
\n\
fullReload = FullReload()\n\
\n\
import mayaHooks\n\
fullReload(mayaHooks)\n\
mayaHooks.main()\n\
\n\
");